// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by internal/extable/gen from table2.csv. DO NOT EDIT.

package ft991a

import cat "github.com/gm5dna/open-rig-programmer/core/cat"

// exItems is the FT-991A's EX address inventory, sorted by (P1,P2,P3),
// built from ONE source: the manual transcription in table2.csv (the
// FT-991A CAT Operation Reference Manual rev 1711-D's menu chart). The
// FT-991A's EX address is a SINGLE component: the chart's three-digit
// MENU Number is P1, every item's P2 and P3 are 0, and the chart prints
// no group labels, so every P1Label and P2Label is "". There are no
// hardware READ observations to join — no FT-991A has ever been asked
// anything — so every item carries the absence sentinels
// ObservedReadWidth 0 and ObservedReadShape "". Regenerate with
// `go generate ./core/cat/ft991a`; do not edit by hand.
//
// EXCLUDED, by address, under ParameterlessExcluded: 87/0/0.
// The chart prints that row with no parameter at all, so it is transcribed
// and counted but names no field an EX frame could read or write.
var exItems = []cat.EXItem{
	{Addr: cat.EXAddress{P1: 1, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "AGC FAST DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 531
	{Addr: cat.EXAddress{P1: 2, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "AGC MID DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 532
	{Addr: cat.EXAddress{P1: 3, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "AGC SLOW DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 533
	{Addr: cat.EXAddress{P1: 4, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "HOME FUNCTION", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 534
	{Addr: cat.EXAddress{P1: 5, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "MY CALL INDICATION", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 535
	{Addr: cat.EXAddress{P1: 6, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "DISPLAY COLOR", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 536
	{Addr: cat.EXAddress{P1: 7, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "DIMMER LED", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 537
	{Addr: cat.EXAddress{P1: 8, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "DIMMER TFT", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 538
	{Addr: cat.EXAddress{P1: 9, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "BAR MTR PEAK HOLD", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 539
	{Addr: cat.EXAddress{P1: 10, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "DVS RX OUT LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 540
	{Addr: cat.EXAddress{P1: 11, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "DVS TX OUT LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 541
	{Addr: cat.EXAddress{P1: 12, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "KEYER TYPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},          // manual line 542
	{Addr: cat.EXAddress{P1: 13, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "KEYER DOT/DASH", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 543
	{Addr: cat.EXAddress{P1: 14, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "CW WEIGHT", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 544
	{Addr: cat.EXAddress{P1: 15, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "BEACON INTERVAL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 545
	{Addr: cat.EXAddress{P1: 16, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "NUMBER STYLE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 546
	{Addr: cat.EXAddress{P1: 17, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "CONTEST NUMBER", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 547
	{Addr: cat.EXAddress{P1: 18, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "CW MEMORY 1", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},         // manual line 548
	{Addr: cat.EXAddress{P1: 19, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "CW MEMORY 2", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},         // manual line 549
	{Addr: cat.EXAddress{P1: 20, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "CW MEMORY 3", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},         // manual line 550
	{Addr: cat.EXAddress{P1: 21, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "CW MEMORY 4", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},         // manual line 551
	{Addr: cat.EXAddress{P1: 22, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "CW MEMORY 5", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},         // manual line 552
	{Addr: cat.EXAddress{P1: 23, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "NB WIDTH", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},            // manual line 553
	{Addr: cat.EXAddress{P1: 24, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "NB REJECTION", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 554
	{Addr: cat.EXAddress{P1: 25, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "NB LEVEL", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},            // manual line 555
	{Addr: cat.EXAddress{P1: 26, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "BEEP LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},          // manual line 556
	{Addr: cat.EXAddress{P1: 27, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "TIME ZONE", Digits: 5, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 557
	{Addr: cat.EXAddress{P1: 28, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "GPS/232C SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 558
	{Addr: cat.EXAddress{P1: 29, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "232C RATE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 559
	{Addr: cat.EXAddress{P1: 30, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "232C TOT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},            // manual line 560
	{Addr: cat.EXAddress{P1: 31, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "CAT RATE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},            // manual line 561
	{Addr: cat.EXAddress{P1: 32, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "CAT TOT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},             // manual line 562
	{Addr: cat.EXAddress{P1: 33, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "CAT RTS", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},             // manual line 563
	{Addr: cat.EXAddress{P1: 34, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "MEM GROUP", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 564
	{Addr: cat.EXAddress{P1: 35, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "QUICK SPLIT FREQ", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 565
	{Addr: cat.EXAddress{P1: 36, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "TX TOT", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},              // manual line 566
	{Addr: cat.EXAddress{P1: 37, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "MIC SCAN", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},            // manual line 567
	{Addr: cat.EXAddress{P1: 38, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "MIC SCAN RESUME", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 568
	{Addr: cat.EXAddress{P1: 39, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "REF FREQ ADJ", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 569
	{Addr: cat.EXAddress{P1: 40, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "CLAR MODE SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 570
	{Addr: cat.EXAddress{P1: 41, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "AM LCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 571
	{Addr: cat.EXAddress{P1: 42, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "AM LCUT SLOPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 572
	{Addr: cat.EXAddress{P1: 43, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "AM HCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 579
	{Addr: cat.EXAddress{P1: 44, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "AM HCUT SLOPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 580
	{Addr: cat.EXAddress{P1: 45, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "AM MIC SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 581
	{Addr: cat.EXAddress{P1: 46, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "AM OUT LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 582
	{Addr: cat.EXAddress{P1: 47, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "AM PTT SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 583
	{Addr: cat.EXAddress{P1: 48, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "AM PORT SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 584
	{Addr: cat.EXAddress{P1: 49, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "AM DATA GAIN", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 585
	{Addr: cat.EXAddress{P1: 50, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "CW LCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 586
	{Addr: cat.EXAddress{P1: 51, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "CW LCUT SLOPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 587
	{Addr: cat.EXAddress{P1: 52, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "CW HCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 588
	{Addr: cat.EXAddress{P1: 53, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "CW HCUT SLOPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 589
	{Addr: cat.EXAddress{P1: 54, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "CW OUT LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 590
	{Addr: cat.EXAddress{P1: 55, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "CW AUTO MODE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 591
	{Addr: cat.EXAddress{P1: 56, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "CW BK-IN TYPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 592
	{Addr: cat.EXAddress{P1: 57, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "CW BK-IN DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 593
	{Addr: cat.EXAddress{P1: 58, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "CW WAVE SHAPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 594
	{Addr: cat.EXAddress{P1: 59, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "CW FREQ DISPLAY", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 595
	{Addr: cat.EXAddress{P1: 60, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "PC KEYING", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 596
	{Addr: cat.EXAddress{P1: 61, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "QSK DELAY TIME", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 597
	{Addr: cat.EXAddress{P1: 62, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "DATA MODE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 598
	{Addr: cat.EXAddress{P1: 63, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "PSK TONE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},            // manual line 599
	{Addr: cat.EXAddress{P1: 64, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "OTHER DISP (SSB)", Digits: 5, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 600
	{Addr: cat.EXAddress{P1: 65, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "OTHER SHIFT (SSB)", Digits: 5, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 601
	{Addr: cat.EXAddress{P1: 66, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "DATA LCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 602
	{Addr: cat.EXAddress{P1: 67, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "DATA LCUT SLOPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 603
	{Addr: cat.EXAddress{P1: 68, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "DATA HCUT FREQ", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 604
	{Addr: cat.EXAddress{P1: 69, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "DATA HCUT SLOPE", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 605
	{Addr: cat.EXAddress{P1: 70, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "DATA IN SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 606
	{Addr: cat.EXAddress{P1: 71, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "DATA PTT SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 607
	{Addr: cat.EXAddress{P1: 72, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "DATA PORT SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 608
	{Addr: cat.EXAddress{P1: 73, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "DATA OUT LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 609
	{Addr: cat.EXAddress{P1: 74, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "FM MIC SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 610
	{Addr: cat.EXAddress{P1: 75, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "FM OUT LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 611
	{Addr: cat.EXAddress{P1: 76, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "FM PKT PTT SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 612
	{Addr: cat.EXAddress{P1: 77, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "FM PKT PORT SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 613
	{Addr: cat.EXAddress{P1: 78, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "FM PKT TX GAIN", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 614
	{Addr: cat.EXAddress{P1: 79, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "FM PKT MODE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},         // manual line 615
	{Addr: cat.EXAddress{P1: 80, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "RPT SHIFT 28MHz", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 616
	{Addr: cat.EXAddress{P1: 81, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "RPT SHIFT 50MHz", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 617
	{Addr: cat.EXAddress{P1: 82, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "RPT SHIFT 144MHz", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 618
	{Addr: cat.EXAddress{P1: 83, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "RPT SHIFT 430MHz", Digits: 5, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 619
	{Addr: cat.EXAddress{P1: 84, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "ARS 144MHz", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},          // manual line 620
	{Addr: cat.EXAddress{P1: 85, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "ARS 430MHz", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},          // manual line 621
	{Addr: cat.EXAddress{P1: 86, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "DCS POLARITY", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 622
	{Addr: cat.EXAddress{P1: 88, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "GM DISPLY", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 624
	{Addr: cat.EXAddress{P1: 89, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "DISTANCE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},            // manual line 625
	{Addr: cat.EXAddress{P1: 90, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "AMS TX MODE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},         // manual line 626
	{Addr: cat.EXAddress{P1: 91, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "STANDBY BEEP", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 627
	{Addr: cat.EXAddress{P1: 92, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "RTTY LCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 628
	{Addr: cat.EXAddress{P1: 93, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "RTTY LCUT SLOPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 629
	{Addr: cat.EXAddress{P1: 94, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "RTTY HCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 630
	{Addr: cat.EXAddress{P1: 95, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "RTTY HCUT SLOPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 631
	{Addr: cat.EXAddress{P1: 96, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "RTTY SHIFT PORT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 632
	{Addr: cat.EXAddress{P1: 97, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "RTTY POLARITY-RX", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 633
	{Addr: cat.EXAddress{P1: 98, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "RTTY POLARITY-TX", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 634
	{Addr: cat.EXAddress{P1: 99, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "RTTY OUT LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 635
	{Addr: cat.EXAddress{P1: 100, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "RTTY SHIFT FREQ", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 636
	{Addr: cat.EXAddress{P1: 101, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "RTTY MARK FREQ", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 637
	{Addr: cat.EXAddress{P1: 102, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "SSB LCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 638
	{Addr: cat.EXAddress{P1: 103, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "SSB LCUT SLOPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 639
	{Addr: cat.EXAddress{P1: 104, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "SSB HCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 640
	{Addr: cat.EXAddress{P1: 105, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "SSB HCUT SLOPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 641
	{Addr: cat.EXAddress{P1: 106, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "SSB MIC SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 642
	{Addr: cat.EXAddress{P1: 107, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "SSB OUT LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 643
	{Addr: cat.EXAddress{P1: 108, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "SSB PTT SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 644
	{Addr: cat.EXAddress{P1: 109, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "SSB PORT SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 645
	{Addr: cat.EXAddress{P1: 110, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "SSB TX BPF", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},         // manual line 646
	{Addr: cat.EXAddress{P1: 111, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "APF WIDTH", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},          // manual line 647
	{Addr: cat.EXAddress{P1: 112, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "CONTOUR LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 648
	{Addr: cat.EXAddress{P1: 113, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "CONTOUR WIDTH", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 649
	{Addr: cat.EXAddress{P1: 114, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "IF NOTCH WIDTH", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 650
	{Addr: cat.EXAddress{P1: 115, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "SCP DISPLAY MODE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 651
	{Addr: cat.EXAddress{P1: 116, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "SCP SPAN FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 652
	{Addr: cat.EXAddress{P1: 117, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "SPECTRUM COLOR", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 653
	{Addr: cat.EXAddress{P1: 118, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "WATER FALL COLOR", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 654
	{Addr: cat.EXAddress{P1: 119, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "PRMTRC EQ1 FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 655
	{Addr: cat.EXAddress{P1: 120, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "PRMTRC EQ1 LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 656
	{Addr: cat.EXAddress{P1: 121, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "PRMTRC EQ1 BWTH", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 657
	{Addr: cat.EXAddress{P1: 122, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "PRMTRC EQ2 FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 658
	{Addr: cat.EXAddress{P1: 123, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "PRMTRC EQ2 LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 659
	{Addr: cat.EXAddress{P1: 124, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "PRMTRC EQ2 BWTH", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 660
	{Addr: cat.EXAddress{P1: 125, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "PRMTRC EQ3 FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 666
	{Addr: cat.EXAddress{P1: 126, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "PRMTRC EQ3 LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 667
	{Addr: cat.EXAddress{P1: 127, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "PRMTRC EQ3 BWTH", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 668
	{Addr: cat.EXAddress{P1: 128, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "P-PRMTRC EQ1 FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 669
	{Addr: cat.EXAddress{P1: 129, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "P-PRMTRC EQ1 LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""}, // manual line 670
	{Addr: cat.EXAddress{P1: 130, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "P-PRMTRC EQ1 BWTH", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 671
	{Addr: cat.EXAddress{P1: 131, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "P-PRMTRC EQ2 FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 672
	{Addr: cat.EXAddress{P1: 132, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "P-PRMTRC EQ2 LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""}, // manual line 673
	{Addr: cat.EXAddress{P1: 133, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "P-PRMTRC EQ2 BWTH", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 674
	{Addr: cat.EXAddress{P1: 134, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "P-PRMTRC EQ3 FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 675
	{Addr: cat.EXAddress{P1: 135, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "P-PRMTRC EQ3 LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""}, // manual line 676
	{Addr: cat.EXAddress{P1: 136, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "P-PRMTRC EQ3 BWTH", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 677
	{Addr: cat.EXAddress{P1: 137, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "HF TX MAX POWER", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 678
	{Addr: cat.EXAddress{P1: 138, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "50M TX MAX POWER", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 679
	{Addr: cat.EXAddress{P1: 139, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "144M TX MAX POWER", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 680
	{Addr: cat.EXAddress{P1: 140, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "430M TX MAX POWER", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 681
	{Addr: cat.EXAddress{P1: 141, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "TUNER SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 682
	{Addr: cat.EXAddress{P1: 142, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "VOX SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},         // manual line 683
	{Addr: cat.EXAddress{P1: 143, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "VOX GAIN", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 684
	{Addr: cat.EXAddress{P1: 144, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "VOX DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},          // manual line 685
	{Addr: cat.EXAddress{P1: 145, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "ANTI VOX GAIN", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 686
	{Addr: cat.EXAddress{P1: 146, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "DATA VOX GAIN", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 687
	{Addr: cat.EXAddress{P1: 147, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "DATA VOX DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 688
	{Addr: cat.EXAddress{P1: 148, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "ANTI DVOX GAIN", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 689
	{Addr: cat.EXAddress{P1: 149, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "EMERGENCY FREQ TX", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 690
	{Addr: cat.EXAddress{P1: 150, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "PRT/WIRES FREQ", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 691
	{Addr: cat.EXAddress{P1: 151, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "PRESET FREQUENCY", Digits: 8, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 692
	{Addr: cat.EXAddress{P1: 152, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "SEARCH SETUP", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 693
	{Addr: cat.EXAddress{P1: 153, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "WIRES DG-ID", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 694
}
