// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by internal/fakets480/gen from transcription-b-480.csv. DO NOT EDIT.

package fakets480

// exWidths480 is this radio's EX (MENU) inventory in compact form: ONE
// WIDTH TOKEN PER MENU NUMBER, and THE STRING'S INDEX IS THE MENU NUMBER —
// this chart runs from 000 with no gaps (480:401). A token is '1' or '2', a
// field of that many raw ASCII bytes of P5 (480:409-411). There is no text
// token: transcription B's text column is validated and deliberately not
// projected (gen/main.go's widthToken says why, and what that does and does
// not claim). ex.go expands this into the address -> default raw P5 map the
// fake answers from.
//
// THE ADDRESS IS A SINGLE COMPONENT: the chart's three-digit Menu number is
// the whole of it, and the frame's P2, P3 and P4 are printed constants, each
// "Always 0 for the TS-480" (480:402-407), rather than address parts.
//
// It is a PROJECTION OF TRANSCRIPTION B — this package's own copy,
// transcription-b-480.csv — derived from that artefact's digits
// column alone. The codec's inventory (core/kw/ts480) is generated from
// transcription A by different code, and core/transport's cross-check proves
// the two agree — so a defect in either transcription or either generator
// shows up there.
//
// 61 menus, 000 to 060. Regenerate with `go generate ./internal/fakets480`;
// gen/main_test.go refuses a file that has drifted from the CSV.
var exWidths480 = "" +
	"1111111111" + // menus 000-009 — transcription-b-480.csv lines 2-11
	"1111111111" + // menus 010-019 — transcription-b-480.csv lines 12-21
	"1111111111" + // menus 020-029 — transcription-b-480.csv lines 22-31
	"1121221111" + // menus 030-039 — transcription-b-480.csv lines 32-41
	"1111111122" + // menus 040-049 — transcription-b-480.csv lines 42-51
	"2221111111" + // menus 050-059 — transcription-b-480.csv lines 52-61
	"1" // menus 060-060 — transcription-b-480.csv line 62
