// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by internal/extable/gen from table2.csv. DO NOT EDIT.

package ft891

import cat "github.com/gm5dna/open-rig-programmer/core/cat"

// exItems is the FT-891's EX address inventory, sorted by (P1,P2), built
// from ONE source: the manual transcription in table2.csv (the FT-891 CAT
// manual rev 1909-C's menu chart). The FT-891's EX address is a PAIR: the
// chart's four-digit MENU Number is P1 and P2, every item's P3 is 0, and
// the chart prints no group labels, so every P1Label and P2Label is "".
// There are no hardware READ observations to join — no FT-891 has ever
// been asked anything — so every item carries the absence sentinels
// ObservedReadWidth 0 and ObservedReadShape "". Regenerate with
// `go generate ./core/cat/ft891`; do not edit by hand.
var exItems = []cat.EXItem{
	{Addr: cat.EXAddress{P1: 1, P2: 1, P3: 0}, P1Label: "", P2Label: "", Name: "AGC FAST DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 525
	{Addr: cat.EXAddress{P1: 1, P2: 2, P3: 0}, P1Label: "", P2Label: "", Name: "AGC MID DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 526
	{Addr: cat.EXAddress{P1: 1, P2: 3, P3: 0}, P1Label: "", P2Label: "", Name: "AGC SLOW DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 527
	{Addr: cat.EXAddress{P1: 2, P2: 1, P3: 0}, P1Label: "", P2Label: "", Name: "LCD CONTRAST", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 528
	{Addr: cat.EXAddress{P1: 2, P2: 2, P3: 0}, P1Label: "", P2Label: "", Name: "DIMMER BACKLIT", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 529
	{Addr: cat.EXAddress{P1: 2, P2: 3, P3: 0}, P1Label: "", P2Label: "", Name: "DIMMER LCD", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 530
	{Addr: cat.EXAddress{P1: 2, P2: 4, P3: 0}, P1Label: "", P2Label: "", Name: "DIMMER TX/BUSY", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 531
	{Addr: cat.EXAddress{P1: 2, P2: 5, P3: 0}, P1Label: "", P2Label: "", Name: "PEAK HOLD", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 532
	{Addr: cat.EXAddress{P1: 2, P2: 6, P3: 0}, P1Label: "", P2Label: "", Name: "ZIN LED", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},          // manual line 533
	{Addr: cat.EXAddress{P1: 2, P2: 7, P3: 0}, P1Label: "", P2Label: "", Name: "POP-UP MENU", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 534
	{Addr: cat.EXAddress{P1: 3, P2: 1, P3: 0}, P1Label: "", P2Label: "", Name: "DVS RX OUT LVL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 535
	{Addr: cat.EXAddress{P1: 3, P2: 2, P3: 0}, P1Label: "", P2Label: "", Name: "DVS TX OUT LVL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 536
	{Addr: cat.EXAddress{P1: 4, P2: 1, P3: 0}, P1Label: "", P2Label: "", Name: "KEYER TYPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 537
	{Addr: cat.EXAddress{P1: 4, P2: 2, P3: 0}, P1Label: "", P2Label: "", Name: "KEYER DOT/DASH", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 538
	{Addr: cat.EXAddress{P1: 4, P2: 3, P3: 0}, P1Label: "", P2Label: "", Name: "CW WEIGHT", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 539
	{Addr: cat.EXAddress{P1: 4, P2: 4, P3: 0}, P1Label: "", P2Label: "", Name: "BEACON INTERVAL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 540
	{Addr: cat.EXAddress{P1: 4, P2: 5, P3: 0}, P1Label: "", P2Label: "", Name: "NUMBER STYLE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 541
	{Addr: cat.EXAddress{P1: 4, P2: 6, P3: 0}, P1Label: "", P2Label: "", Name: "CONTEST NUMBER", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 542
	{Addr: cat.EXAddress{P1: 4, P2: 7, P3: 0}, P1Label: "", P2Label: "", Name: "CW MEMORY 1", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 543
	{Addr: cat.EXAddress{P1: 4, P2: 8, P3: 0}, P1Label: "", P2Label: "", Name: "CW MEMORY 2", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 544
	{Addr: cat.EXAddress{P1: 4, P2: 9, P3: 0}, P1Label: "", P2Label: "", Name: "CW MEMORY 3", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 545
	{Addr: cat.EXAddress{P1: 4, P2: 10, P3: 0}, P1Label: "", P2Label: "", Name: "CW MEMORY 4", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 546
	{Addr: cat.EXAddress{P1: 4, P2: 11, P3: 0}, P1Label: "", P2Label: "", Name: "CW MEMORY 5", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 547
	{Addr: cat.EXAddress{P1: 5, P2: 1, P3: 0}, P1Label: "", P2Label: "", Name: "NB WIDTH", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},         // manual line 548
	{Addr: cat.EXAddress{P1: 5, P2: 2, P3: 0}, P1Label: "", P2Label: "", Name: "NB REJECTION", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 549
	{Addr: cat.EXAddress{P1: 5, P2: 3, P3: 0}, P1Label: "", P2Label: "", Name: "NB LEVEL", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},         // manual line 550
	{Addr: cat.EXAddress{P1: 5, P2: 4, P3: 0}, P1Label: "", P2Label: "", Name: "BEEP LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 551
	{Addr: cat.EXAddress{P1: 5, P2: 5, P3: 0}, P1Label: "", P2Label: "", Name: "RF/SQL VR", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 552
	{Addr: cat.EXAddress{P1: 5, P2: 6, P3: 0}, P1Label: "", P2Label: "", Name: "CAT RATE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},         // manual line 553
	{Addr: cat.EXAddress{P1: 5, P2: 7, P3: 0}, P1Label: "", P2Label: "", Name: "CAT TOT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},          // manual line 554
	{Addr: cat.EXAddress{P1: 5, P2: 8, P3: 0}, P1Label: "", P2Label: "", Name: "CAT RTS", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},          // manual line 555
	{Addr: cat.EXAddress{P1: 5, P2: 9, P3: 0}, P1Label: "", P2Label: "", Name: "MEM GROUP", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 561
	{Addr: cat.EXAddress{P1: 5, P2: 10, P3: 0}, P1Label: "", P2Label: "", Name: "FM SETTING", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 562
	{Addr: cat.EXAddress{P1: 5, P2: 11, P3: 0}, P1Label: "", P2Label: "", Name: "REC SETTING", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 563
	{Addr: cat.EXAddress{P1: 5, P2: 12, P3: 0}, P1Label: "", P2Label: "", Name: "ATAS SETTING", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 564
	{Addr: cat.EXAddress{P1: 5, P2: 13, P3: 0}, P1Label: "", P2Label: "", Name: "QUICK SPL FREQ", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 565
	{Addr: cat.EXAddress{P1: 5, P2: 14, P3: 0}, P1Label: "", P2Label: "", Name: "TX TOT", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},          // manual line 566
	{Addr: cat.EXAddress{P1: 5, P2: 15, P3: 0}, P1Label: "", P2Label: "", Name: "MIC SCAN", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 567
	{Addr: cat.EXAddress{P1: 5, P2: 16, P3: 0}, P1Label: "", P2Label: "", Name: "MIC SCAN RESUME", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""}, // manual line 568
	{Addr: cat.EXAddress{P1: 5, P2: 17, P3: 0}, P1Label: "", P2Label: "", Name: "REF FREQ ADJ", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 569
	{Addr: cat.EXAddress{P1: 5, P2: 18, P3: 0}, P1Label: "", P2Label: "", Name: "CLAR SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 570
	{Addr: cat.EXAddress{P1: 5, P2: 19, P3: 0}, P1Label: "", P2Label: "", Name: "APO", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},             // manual line 571
	{Addr: cat.EXAddress{P1: 5, P2: 20, P3: 0}, P1Label: "", P2Label: "", Name: "FAN CONTROL", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 572
	{Addr: cat.EXAddress{P1: 6, P2: 1, P3: 0}, P1Label: "", P2Label: "", Name: "AM LCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 573
	{Addr: cat.EXAddress{P1: 6, P2: 2, P3: 0}, P1Label: "", P2Label: "", Name: "AM LCUT SLOPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 574
	{Addr: cat.EXAddress{P1: 6, P2: 3, P3: 0}, P1Label: "", P2Label: "", Name: "AM HCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 575
	{Addr: cat.EXAddress{P1: 6, P2: 4, P3: 0}, P1Label: "", P2Label: "", Name: "AM HCUT SLOPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 576
	{Addr: cat.EXAddress{P1: 6, P2: 5, P3: 0}, P1Label: "", P2Label: "", Name: "AM MIC SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 577
	{Addr: cat.EXAddress{P1: 6, P2: 6, P3: 0}, P1Label: "", P2Label: "", Name: "AM OUT LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 578
	{Addr: cat.EXAddress{P1: 6, P2: 7, P3: 0}, P1Label: "", P2Label: "", Name: "AM PTT SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 579
	{Addr: cat.EXAddress{P1: 7, P2: 1, P3: 0}, P1Label: "", P2Label: "", Name: "CW LCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 580
	{Addr: cat.EXAddress{P1: 7, P2: 2, P3: 0}, P1Label: "", P2Label: "", Name: "CW LCUT SLOPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 581
	{Addr: cat.EXAddress{P1: 7, P2: 3, P3: 0}, P1Label: "", P2Label: "", Name: "CW HCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 582
	{Addr: cat.EXAddress{P1: 7, P2: 4, P3: 0}, P1Label: "", P2Label: "", Name: "CW HCUT SLOPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 583
	{Addr: cat.EXAddress{P1: 7, P2: 5, P3: 0}, P1Label: "", P2Label: "", Name: "CW OUT LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 584
	{Addr: cat.EXAddress{P1: 7, P2: 6, P3: 0}, P1Label: "", P2Label: "", Name: "CW AUTO MODE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 585
	{Addr: cat.EXAddress{P1: 7, P2: 7, P3: 0}, P1Label: "", P2Label: "", Name: "CW BFO", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 586
	{Addr: cat.EXAddress{P1: 7, P2: 8, P3: 0}, P1Label: "", P2Label: "", Name: "CW BK-IN TYPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 587
	{Addr: cat.EXAddress{P1: 7, P2: 9, P3: 0}, P1Label: "", P2Label: "", Name: "CW BK-IN DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 588
	{Addr: cat.EXAddress{P1: 7, P2: 10, P3: 0}, P1Label: "", P2Label: "", Name: "CW WAVE SHAPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 589
	{Addr: cat.EXAddress{P1: 7, P2: 11, P3: 0}, P1Label: "", P2Label: "", Name: "CW FREQ DISPLAY", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""}, // manual line 590
	{Addr: cat.EXAddress{P1: 7, P2: 12, P3: 0}, P1Label: "", P2Label: "", Name: "PC KEYING", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 591
	{Addr: cat.EXAddress{P1: 7, P2: 13, P3: 0}, P1Label: "", P2Label: "", Name: "QSK DELAY TIME", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 592
	{Addr: cat.EXAddress{P1: 8, P2: 1, P3: 0}, P1Label: "", P2Label: "", Name: "DATA MODE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 593
	{Addr: cat.EXAddress{P1: 8, P2: 2, P3: 0}, P1Label: "", P2Label: "", Name: "PSK TONE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},         // manual line 594
	{Addr: cat.EXAddress{P1: 8, P2: 3, P3: 0}, P1Label: "", P2Label: "", Name: "OTHER DISP", Digits: 5, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 595
	{Addr: cat.EXAddress{P1: 8, P2: 4, P3: 0}, P1Label: "", P2Label: "", Name: "OTHER SHIFT", Digits: 5, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 596
	{Addr: cat.EXAddress{P1: 8, P2: 5, P3: 0}, P1Label: "", P2Label: "", Name: "DATA LCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 597
	{Addr: cat.EXAddress{P1: 8, P2: 6, P3: 0}, P1Label: "", P2Label: "", Name: "DATA LCUT SLOPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 598
	{Addr: cat.EXAddress{P1: 8, P2: 7, P3: 0}, P1Label: "", P2Label: "", Name: "DATA HCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 599
	{Addr: cat.EXAddress{P1: 8, P2: 8, P3: 0}, P1Label: "", P2Label: "", Name: "DATA HCUT SLOPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 600
	{Addr: cat.EXAddress{P1: 8, P2: 9, P3: 0}, P1Label: "", P2Label: "", Name: "DATA IN SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 601
	{Addr: cat.EXAddress{P1: 8, P2: 10, P3: 0}, P1Label: "", P2Label: "", Name: "DATA PTT SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""}, // manual line 602
	{Addr: cat.EXAddress{P1: 8, P2: 11, P3: 0}, P1Label: "", P2Label: "", Name: "DATA OUT LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 603
	{Addr: cat.EXAddress{P1: 8, P2: 12, P3: 0}, P1Label: "", P2Label: "", Name: "DATA BFO", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 604
	{Addr: cat.EXAddress{P1: 9, P2: 1, P3: 0}, P1Label: "", P2Label: "", Name: "FM MIC SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 605
	{Addr: cat.EXAddress{P1: 9, P2: 2, P3: 0}, P1Label: "", P2Label: "", Name: "FM OUT LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 606
	{Addr: cat.EXAddress{P1: 9, P2: 3, P3: 0}, P1Label: "", P2Label: "", Name: "PKT PTT SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 607
	{Addr: cat.EXAddress{P1: 9, P2: 4, P3: 0}, P1Label: "", P2Label: "", Name: "RPT SHIFT 28MHz", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 608
	{Addr: cat.EXAddress{P1: 9, P2: 5, P3: 0}, P1Label: "", P2Label: "", Name: "RPT SHIFT 50MHz", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 609
	{Addr: cat.EXAddress{P1: 9, P2: 6, P3: 0}, P1Label: "", P2Label: "", Name: "DCS POLARITY", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 610
	{Addr: cat.EXAddress{P1: 10, P2: 1, P3: 0}, P1Label: "", P2Label: "", Name: "RTTY LCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 611
	{Addr: cat.EXAddress{P1: 10, P2: 2, P3: 0}, P1Label: "", P2Label: "", Name: "RTTY LCUT SLOPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""}, // manual line 612
	{Addr: cat.EXAddress{P1: 10, P2: 3, P3: 0}, P1Label: "", P2Label: "", Name: "RTTY HCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 613
	{Addr: cat.EXAddress{P1: 10, P2: 4, P3: 0}, P1Label: "", P2Label: "", Name: "RTTY HCUT SLOPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""}, // manual line 614
	{Addr: cat.EXAddress{P1: 10, P2: 5, P3: 0}, P1Label: "", P2Label: "", Name: "RTTY SHIFT PORT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""}, // manual line 615
	{Addr: cat.EXAddress{P1: 10, P2: 6, P3: 0}, P1Label: "", P2Label: "", Name: "RTTY POLARITY-R", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""}, // manual line 616
	{Addr: cat.EXAddress{P1: 10, P2: 7, P3: 0}, P1Label: "", P2Label: "", Name: "RTTY POLARITY-T", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""}, // manual line 617
	{Addr: cat.EXAddress{P1: 10, P2: 8, P3: 0}, P1Label: "", P2Label: "", Name: "RTTY OUT LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 618
	{Addr: cat.EXAddress{P1: 10, P2: 9, P3: 0}, P1Label: "", P2Label: "", Name: "RTTY SHIFT FREQ", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""}, // manual line 619
	{Addr: cat.EXAddress{P1: 10, P2: 10, P3: 0}, P1Label: "", P2Label: "", Name: "RTTY MARK FREQ", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""}, // manual line 620
	{Addr: cat.EXAddress{P1: 10, P2: 11, P3: 0}, P1Label: "", P2Label: "", Name: "RTTY BFO", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 621
	{Addr: cat.EXAddress{P1: 11, P2: 1, P3: 0}, P1Label: "", P2Label: "", Name: "SSB LCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 622
	{Addr: cat.EXAddress{P1: 11, P2: 2, P3: 0}, P1Label: "", P2Label: "", Name: "SSB LCUT SLOPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 623
	{Addr: cat.EXAddress{P1: 11, P2: 3, P3: 0}, P1Label: "", P2Label: "", Name: "SSB HCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 624
	{Addr: cat.EXAddress{P1: 11, P2: 4, P3: 0}, P1Label: "", P2Label: "", Name: "SSB HCUT SLOPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 625
	{Addr: cat.EXAddress{P1: 11, P2: 5, P3: 0}, P1Label: "", P2Label: "", Name: "SSB MIC SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 626
	{Addr: cat.EXAddress{P1: 11, P2: 6, P3: 0}, P1Label: "", P2Label: "", Name: "SSB OUT LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 627
	{Addr: cat.EXAddress{P1: 11, P2: 7, P3: 0}, P1Label: "", P2Label: "", Name: "SSB BFO", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},         // manual line 628
	{Addr: cat.EXAddress{P1: 11, P2: 8, P3: 0}, P1Label: "", P2Label: "", Name: "SSB PTT SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 629
	{Addr: cat.EXAddress{P1: 11, P2: 9, P3: 0}, P1Label: "", P2Label: "", Name: "SSB TX BPF", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 630
	{Addr: cat.EXAddress{P1: 12, P2: 1, P3: 0}, P1Label: "", P2Label: "", Name: "APF WIDTH", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 631
	{Addr: cat.EXAddress{P1: 12, P2: 2, P3: 0}, P1Label: "", P2Label: "", Name: "CONTOUR LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 632
	{Addr: cat.EXAddress{P1: 12, P2: 3, P3: 0}, P1Label: "", P2Label: "", Name: "CONTOUR WIDTH", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 633
	{Addr: cat.EXAddress{P1: 12, P2: 4, P3: 0}, P1Label: "", P2Label: "", Name: "IF NOTCH WIDTH", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 634
	{Addr: cat.EXAddress{P1: 13, P2: 1, P3: 0}, P1Label: "", P2Label: "", Name: "SCP START CYCLE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""}, // manual line 635
	{Addr: cat.EXAddress{P1: 13, P2: 2, P3: 0}, P1Label: "", P2Label: "", Name: "SCP SPAN FREQ", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 636
	{Addr: cat.EXAddress{P1: 14, P2: 1, P3: 0}, P1Label: "", P2Label: "", Name: "QUICK DIAL", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 637
	{Addr: cat.EXAddress{P1: 14, P2: 2, P3: 0}, P1Label: "", P2Label: "", Name: "SSB DIAL STEP", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 638
	{Addr: cat.EXAddress{P1: 14, P2: 3, P3: 0}, P1Label: "", P2Label: "", Name: "AM DIAL STEP", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 639
	{Addr: cat.EXAddress{P1: 14, P2: 4, P3: 0}, P1Label: "", P2Label: "", Name: "FM DIAL STEP", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 640
	{Addr: cat.EXAddress{P1: 14, P2: 5, P3: 0}, P1Label: "", P2Label: "", Name: "DIAL STEP", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 641
	{Addr: cat.EXAddress{P1: 14, P2: 6, P3: 0}, P1Label: "", P2Label: "", Name: "AM CH STEP", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 642
	{Addr: cat.EXAddress{P1: 14, P2: 7, P3: 0}, P1Label: "", P2Label: "", Name: "FM CH STEP", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 648
	{Addr: cat.EXAddress{P1: 15, P2: 1, P3: 0}, P1Label: "", P2Label: "", Name: "EQ1 FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 649
	{Addr: cat.EXAddress{P1: 15, P2: 2, P3: 0}, P1Label: "", P2Label: "", Name: "EQ1 LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 650
	{Addr: cat.EXAddress{P1: 15, P2: 3, P3: 0}, P1Label: "", P2Label: "", Name: "EQ1 BWTH", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 651
	{Addr: cat.EXAddress{P1: 15, P2: 4, P3: 0}, P1Label: "", P2Label: "", Name: "EQ2 FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 653
	{Addr: cat.EXAddress{P1: 15, P2: 5, P3: 0}, P1Label: "", P2Label: "", Name: "EQ2 LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 655
	{Addr: cat.EXAddress{P1: 15, P2: 6, P3: 0}, P1Label: "", P2Label: "", Name: "EQ2 BWTH", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 656
	{Addr: cat.EXAddress{P1: 15, P2: 7, P3: 0}, P1Label: "", P2Label: "", Name: "EQ3 FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 657
	{Addr: cat.EXAddress{P1: 15, P2: 8, P3: 0}, P1Label: "", P2Label: "", Name: "EQ3 LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 658
	{Addr: cat.EXAddress{P1: 15, P2: 9, P3: 0}, P1Label: "", P2Label: "", Name: "EQ3 BWTH", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 659
	{Addr: cat.EXAddress{P1: 15, P2: 10, P3: 0}, P1Label: "", P2Label: "", Name: "P-EQ1 FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 660
	{Addr: cat.EXAddress{P1: 15, P2: 11, P3: 0}, P1Label: "", P2Label: "", Name: "P-EQ1 LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 661
	{Addr: cat.EXAddress{P1: 15, P2: 12, P3: 0}, P1Label: "", P2Label: "", Name: "P-EQ1 BWTH", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 662
	{Addr: cat.EXAddress{P1: 15, P2: 13, P3: 0}, P1Label: "", P2Label: "", Name: "P-EQ2 FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 664
	{Addr: cat.EXAddress{P1: 15, P2: 14, P3: 0}, P1Label: "", P2Label: "", Name: "P-EQ2 LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 666
	{Addr: cat.EXAddress{P1: 15, P2: 15, P3: 0}, P1Label: "", P2Label: "", Name: "P-EQ2 BWTH", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 667
	{Addr: cat.EXAddress{P1: 15, P2: 16, P3: 0}, P1Label: "", P2Label: "", Name: "P-EQ3 FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 668
	{Addr: cat.EXAddress{P1: 15, P2: 17, P3: 0}, P1Label: "", P2Label: "", Name: "P-EQ3 LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 669
	{Addr: cat.EXAddress{P1: 15, P2: 18, P3: 0}, P1Label: "", P2Label: "", Name: "P-EQ3 BWTH", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 670
	{Addr: cat.EXAddress{P1: 16, P2: 1, P3: 0}, P1Label: "", P2Label: "", Name: "HF SSB PWR", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 671
	{Addr: cat.EXAddress{P1: 16, P2: 2, P3: 0}, P1Label: "", P2Label: "", Name: "HF AM PWR", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 672
	{Addr: cat.EXAddress{P1: 16, P2: 3, P3: 0}, P1Label: "", P2Label: "", Name: "HF PWR", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},          // manual line 673
	{Addr: cat.EXAddress{P1: 16, P2: 4, P3: 0}, P1Label: "", P2Label: "", Name: "50M SSB PWR", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 674
	{Addr: cat.EXAddress{P1: 16, P2: 5, P3: 0}, P1Label: "", P2Label: "", Name: "50M AM PWR", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 675
	{Addr: cat.EXAddress{P1: 16, P2: 6, P3: 0}, P1Label: "", P2Label: "", Name: "50M PWR", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},         // manual line 676
	{Addr: cat.EXAddress{P1: 16, P2: 7, P3: 0}, P1Label: "", P2Label: "", Name: "SSB MIC GAIN", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 677
	{Addr: cat.EXAddress{P1: 16, P2: 8, P3: 0}, P1Label: "", P2Label: "", Name: "AM MIC GAIN", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 678
	{Addr: cat.EXAddress{P1: 16, P2: 9, P3: 0}, P1Label: "", P2Label: "", Name: "FM MIC GAIN", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 679
	{Addr: cat.EXAddress{P1: 16, P2: 10, P3: 0}, P1Label: "", P2Label: "", Name: "DATA MIC GAIN", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 680
	{Addr: cat.EXAddress{P1: 16, P2: 11, P3: 0}, P1Label: "", P2Label: "", Name: "SSB DATA GAIN", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 681
	{Addr: cat.EXAddress{P1: 16, P2: 12, P3: 0}, P1Label: "", P2Label: "", Name: "AM DATA GAIN", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 682
	{Addr: cat.EXAddress{P1: 16, P2: 13, P3: 0}, P1Label: "", P2Label: "", Name: "FM DATA GAIN", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 683
	{Addr: cat.EXAddress{P1: 16, P2: 14, P3: 0}, P1Label: "", P2Label: "", Name: "DATA DATA GAIN", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""}, // manual line 684
	{Addr: cat.EXAddress{P1: 16, P2: 15, P3: 0}, P1Label: "", P2Label: "", Name: "TUNER SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 685
	{Addr: cat.EXAddress{P1: 16, P2: 16, P3: 0}, P1Label: "", P2Label: "", Name: "VOX SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 686
	{Addr: cat.EXAddress{P1: 16, P2: 17, P3: 0}, P1Label: "", P2Label: "", Name: "VOX GAIN", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 687
	{Addr: cat.EXAddress{P1: 16, P2: 18, P3: 0}, P1Label: "", P2Label: "", Name: "VOX DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 688
	{Addr: cat.EXAddress{P1: 16, P2: 19, P3: 0}, P1Label: "", P2Label: "", Name: "ANTI VOX GAIN", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 689
	{Addr: cat.EXAddress{P1: 16, P2: 20, P3: 0}, P1Label: "", P2Label: "", Name: "DATA VOX GAIN", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 690
	{Addr: cat.EXAddress{P1: 16, P2: 21, P3: 0}, P1Label: "", P2Label: "", Name: "DATA VOX DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""}, // manual line 691
	{Addr: cat.EXAddress{P1: 16, P2: 22, P3: 0}, P1Label: "", P2Label: "", Name: "ANTI DVOX GAIN", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""}, // manual line 692
	{Addr: cat.EXAddress{P1: 16, P2: 23, P3: 0}, P1Label: "", P2Label: "", Name: "EMERGENCY FREQ", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""}, // manual line 693
	{Addr: cat.EXAddress{P1: 17, P2: 1, P3: 0}, P1Label: "", P2Label: "", Name: "RESET", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 694
	{Addr: cat.EXAddress{P1: 18, P2: 1, P3: 0}, P1Label: "", P2Label: "", Name: "MAIN VERSION", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 695
	{Addr: cat.EXAddress{P1: 18, P2: 2, P3: 0}, P1Label: "", P2Label: "", Name: "DSP VERSION", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 696
	{Addr: cat.EXAddress{P1: 18, P2: 3, P3: 0}, P1Label: "", P2Label: "", Name: "LCD VERSION", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 697
}
