// SPDX-License-Identifier: GPL-3.0-or-later

package main

import (
	"flag"
	"fmt"
	"io"
	"strconv"
	"strings"

	"github.com/gm5dna/open-rig-programmer/internal/wiring"
)

// writeBoundaryArg is the reserved first positional that selects "rigprog
// settings write-boundary" — the milestone's ONE DEVIATION from plan.md's
// task (h2): the plan expected (b2)'s generator to emit this safety-
// boundary data file directly, but that generator has no denylist
// awareness by design (the denylist is applied only in core/cat's FT710
// dialect constructor, dialect.go's buildFT710ExWrite). This sub-mode
// dumps the SAME data from core/cat's side instead, after the filter has
// already run. Reserved on diff-observed's own precedent: a codeplug file
// called "write-boundary" cannot be given to plain "rigprog settings" and
// must be named something else.
const writeBoundaryArg = "write-boundary"

// writeBoundaryHeader is written verbatim before the CSV header row. It
// states, plainly, the one fact everything downstream of this file
// depends on: it is the ONLY thing keeping the out-of-repo Session W
// bench tool off the 58 denied and 4 held addresses (spec §1) and off
// illegal values at every admitted one — that tool cannot import core/cat
// (spec §3) and has no independent way to know which addresses are safe
// to Set or what values are legal at each. The tool TRUSTS this file
// completely: nothing checks a hand-tampered row against the real
// denylist at Set time.
const writeBoundaryHeader = `# FT-710 EX write-boundary (task h2 — Session W bench-tool safety boundary).
#
# GENERATED by "rigprog settings write-boundary" from this build's own
# core/cat write descriptor: core/cat/exwrite_gen.go filtered through
# core/cat/exdenylist.go's denylist/held predicates (core/cat/dialect.go's
# buildFT710ExWrite). One row per address ADMITTED for characterisation —
# every denied (58) and held (4) address is absent from this file BY
# CONSTRUCTION, never by a runtime check the bench tool performs itself.
#
# THIS FILE IS THE ONLY THING KEEPING THE OUT-OF-REPO SESSION W BENCH TOOL
# OFF THE DENIED/HELD ADDRESSES AND OFF ILLEGAL VALUES. The bench tool
# (docs/fixtures-private/session-w/, gitignored) must not and does not
# import core/cat (spec §3) — this file is its entire view of which
# addresses exist to characterise and what values are legal at each.
# Regenerate with "rigprog settings write-boundary --out FILE --force"
# immediately before every Session W run; never hand-edit it — a tampered
# row is trusted exactly like a real one, except where its own width/
# domain fields are empty (see the bench tool's own README).
#
# Columns: id,read_width,width,codes,lo,hi,step,signed
#   id          P1P2P3 EX address, 3, 4, 5 or 6 ASCII digits per
#               core/codeplug's isSettingIDWidth (the FT-710's own EX ids
#               are always 6, e.g. "010101")
#   read_width  the manual's Digits column (core/cat.EXItem.Digits) — a
#               READ width, never a Set width (core/cat/exinventory.go's
#               own warning: read width must never size a Set)
#   width       ObservedSetWidth: 0 until Session W characterises this
#               address's Set width — the rendered sentinel this build
#               ships, not an omission
#   codes       enumerated legal codes, ';'-separated, empty if none
#   lo,hi,step  the legal stepped range; hi == 0 means no range
#   signed      true if the range's wire form carries an explicit sign
#               character (-00 and +00 are two distinct legal codes)
`

// writeBoundaryCSVHeader is the exact, ordered column set.
const writeBoundaryCSVHeader = "id,read_width,width,codes,lo,hi,step,signed"

// writeBoundaryCSV writes header + rows to w, hand-rolled rather than
// encoding/csv: every field is either digits, ';'-joined digits, or a
// fixed "true"/"false" word — nothing here can ever need quoting or
// escaping, unlike the free-text label columns "rigprog settings" itself
// writes (writeSettingsCSV).
//
// rows is built by core/driver/ft710.WriteBoundaryRows (reached via
// wiring.FT710WriteBoundaryRows, task h2 guard fix) rather than here: this
// package may not import core/cat, and deriving a row needs the dialect's
// own EXItems/EXWriteDescriptor, both core/cat-typed (internal/guards'
// composition-root discipline).
func writeBoundaryCSV(w io.Writer, rows []wiring.FT710WriteBoundaryRow) error {
	if _, err := io.WriteString(w, writeBoundaryHeader); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, writeBoundaryCSVHeader); err != nil {
		return err
	}
	for _, r := range rows {
		codes := make([]string, len(r.Codes))
		for i, c := range r.Codes {
			codes[i] = strconv.Itoa(c)
		}
		if _, err := fmt.Fprintf(w, "%s,%d,%d,%s,%d,%d,%d,%t\n",
			r.ID, r.ReadWidth, r.Width, strings.Join(codes, ";"), r.Lo, r.Hi, r.Step, r.Signed); err != nil {
			return fmt.Errorf("rigprog settings write-boundary: writing row %q: %w", r.ID, err)
		}
	}
	return nil
}

// settingsWriteBoundary implements "rigprog settings write-boundary
// [--out FILE] [--force]" (task-h2 brief): dump the FT-710 write gate's
// own admitted-address boundary — the safety-critical data file the
// out-of-repo Session W bench tool reads and trusts completely, since it
// cannot import core/cat itself. OFFLINE, like every other "rigprog
// settings" mode — no --port/--fake here either, and no radio identity is
// consulted: this dumps a BUILD-time fact (this binary's own core/cat
// descriptor table), not anything read from a file or a radio.
func settingsWriteBoundary(args []string, stdout, stderr io.Writer) int {
	const name = "settings write-boundary"
	fs := flag.NewFlagSet(name, flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	out := fs.String("out", "", "write the boundary CSV to this file path instead of stdout")
	force := fs.Bool("force", false, "overwrite --out if it already exists")

	if ok, code := parseArgs(fs, args, name, printSettingsWriteBoundaryUsage, stdout, stderr); !ok {
		return code
	}
	if fs.NArg() != 0 {
		fmt.Fprintf(stderr, "rigprog %s: takes no positional arguments\n", name)
		printSettingsWriteBoundaryUsage(stderr)
		return exitUsage
	}

	rows := wiring.FT710WriteBoundaryRows()

	if *out == "" {
		if err := writeBoundaryCSV(stdout, rows); err != nil {
			fmt.Fprintf(stderr, "rigprog %s: writing stdout: %v\n", name, err)
			return exitError
		}
		return exitSuccess
	}

	refused, err := checkOverwrite(*out, *force)
	if err != nil {
		fmt.Fprintf(stderr, "rigprog %s: checking %s: %v\n", name, *out, err)
		return exitError
	}
	if refused {
		fmt.Fprintf(stderr, "rigprog %s: %s already exists; use --force to overwrite\n", name, *out)
		return exitError
	}

	f, err := openCSVCommit(*out, *force)
	if err != nil {
		fmt.Fprintf(stderr, "rigprog %s: creating %s: %v\n", name, *out, err)
		return exitError
	}
	if err := writeBoundaryCSV(f, rows); err != nil {
		f.Close()
		fmt.Fprintf(stderr, "rigprog %s: writing %s: %v\n", name, *out, err)
		return exitError
	}
	if err := f.Close(); err != nil {
		fmt.Fprintf(stderr, "rigprog %s: closing %s: %v\n", name, *out, err)
		return exitError
	}

	fmt.Fprintf(stdout, "Addresses written: %d\n", len(rows))
	fmt.Fprintf(stdout, "Output:            %s\n", *out)
	return exitSuccess
}
