// SPDX-License-Identifier: GPL-3.0-or-later

package ts480_test

import (
	"bytes"
	"fmt"
	"os"
	"strings"
	"testing"

	"github.com/gm5dna/open-rig-programmer/core/kw/ts480"
	"github.com/gm5dna/open-rig-programmer/internal/extable"
)

// ts480Profile selects THE ts480 registration and refuses to guess.
//
// IT SELECTS BY THE (Package, VarName) PAIR, NOT BY Package ALONE, and that is
// not defensive habit: core/kw/ts590 carries TWO registrations in one package
// directory — the TS-590S's and the TS-590SG's — so a package-only filter in
// this family returns whichever the registry enumerated first. That would be
// silently the wrong radio half the time in the sibling package, and a
// selector written the wrong way here would be copied there. The pair is the
// same key validateRegistry proves unique (its Package + "." + VarName
// collision map), so exactly one registration can ever match.
//
// The alternative the spec names is Lookup("ts480"). Both are permitted; the
// pair is used because it keeps this file free of the registry's lookup name,
// which is a CLI token rather than a fact about the radio.
func ts480Profile(t *testing.T) extable.Profile {
	t.Helper()
	var matches []extable.NamedProfile
	for _, np := range extable.RegisteredProfiles() {
		if np.Profile.Package == "ts480" && np.Profile.VarName == "exItems480" {
			matches = append(matches, np)
		}
	}
	if len(matches) != 1 {
		t.Fatalf("registry holds %d profiles with Package ts480 and VarName exItems480, want exactly 1: %v", len(matches), names(matches))
	}
	return matches[0].Profile
}

// TestEXInventoryGenerated_NotStale re-derives this package's generated
// inventory from its ONE source — menu480.csv, the manual transcription — and
// byte-compares the result with the committed exinventory_gen.go. It is the CI
// guard for the generator: CI runs plain `go test ./...` and never
// `go generate`, so without this test an edit to menu480.csv that was not
// regenerated, or a hand-edit of the generated file, would ship silently. On
// failure, run `go generate ./core/kw/ts480` and commit the result.
//
// It is also what makes T5's BOOTSTRAP file impossible to ship. That file
// declares an EMPTY exItems480 so the package compiles before this
// transcription exists, and an empty menu table is a defect that presents
// itself as a valid one — RenderGo's own ExpectedRows check refuses to render
// 0 rows, so this comparison fails loudly against the placeholder.
func TestEXInventoryGenerated_NotStale(t *testing.T) {
	p := ts480Profile(t)

	csv, err := os.ReadFile(p.ManualCSV)
	if err != nil {
		t.Fatalf("reading %s: %v", p.ManualCSV, err)
	}
	rows, err := extable.ParseCSV(p, csv)
	if err != nil {
		t.Fatalf("ParseCSV(%s): %v", p.ManualCSV, err)
	}
	// ObservationsAbsent: RenderGo requires the observation map to be EMPTY
	// rather than partial, so nil is the correct argument and not a stand-in
	// for an unread file.
	want, err := extable.RenderGo(p, rows, nil)
	if err != nil {
		t.Fatalf("RenderGo: %v", err)
	}

	got, err := os.ReadFile(p.OutFile)
	if err != nil {
		t.Fatalf("reading %s: %v", p.OutFile, err)
	}

	if !bytes.Equal(got, want) {
		t.Errorf("%s is stale relative to %s; run `go generate ./core/kw/ts480` and commit the result (regenerated %d bytes, committed %d bytes)", p.OutFile, p.ManualCSV, len(want), len(got))
	}
}

// TestEXInventory_LengthIsExpectedRows asserts over the SHIPPING accessor what
// the staleness test asserts over the generated bytes: the menu table this
// package publishes has exactly the number of addresses the profile declares.
//
// It is a separate test from the byte comparison because the two fail for
// different reasons and a reader needs to know which. A stale generated file
// is a "run go generate" problem; an inventory of the wrong LENGTH is a
// transcription or a domain problem, and against the bootstrap placeholder it
// is the one that says so in one line. ExpectedRows is A26's number for this
// radio and comes from the boundary ledger, never from this file.
func TestEXInventory_LengthIsExpectedRows(t *testing.T) {
	p := ts480Profile(t)
	if got := len(ts480.EXItems()); got != p.ExpectedRows {
		t.Errorf("EXItems() has %d rows, want the profile's ExpectedRows %d — the TS-480's printed domain is 000 ~ 060", got, p.ExpectedRows)
	}
}

// TestParseCSV_RefusesADeletedRow is the completeness red proof: RenderGo
// compares its two supplied sources against each other only, so a source that
// lost a row would render happily were ExpectedRows not consulted. Deleting
// ONE data row from the committed CSV must fail.
//
// The deletion is done on an in-memory copy. Nothing on disk is touched, so
// the proof is permanent rather than a one-off experiment in a terminal.
func TestParseCSV_RefusesADeletedRow(t *testing.T) {
	p := ts480Profile(t)
	csv, err := os.ReadFile(p.ManualCSV)
	if err != nil {
		t.Fatalf("reading %s: %v", p.ManualCSV, err)
	}
	short := dropLastDataRow(t, csv)

	rows, err := extable.ParseCSV(p, short)
	if err != nil {
		t.Fatalf("ParseCSV on the shortened CSV: %v — the row was expected to parse and be refused by RenderGo's count", err)
	}
	if len(rows) != p.ExpectedRows-1 {
		t.Fatalf("shortened CSV parsed %d rows, want %d — the fixture did not remove exactly one row", len(rows), p.ExpectedRows-1)
	}
	if _, err := extable.RenderGo(p, rows, nil); err == nil {
		t.Error("RenderGo accepted an inventory one row short of ExpectedRows; a truncated transcription would ship")
	}
}

// TestParseCSV_RefusesANonZeroP2OrP3 is the AddressSingle red proof, in both
// components. The TS-480's printed Menu No. is the WHOLE address: the EX frame
// is "E X P1 P1 P1 P2 P2 P3 P4 ;" with P2 always "00" and P3 always '0'
// (480:402-407), so a non-zero p2 or p3 column names something no frame can
// express.
//
// IT MUST BE REFUSED, NOT DROPPED, and that is the half worth proving: a
// component silently discarded here would reach the generated inventory as a 0
// that nothing recorded having changed, and the row would look correct.
func TestParseCSV_RefusesANonZeroP2OrP3(t *testing.T) {
	p := ts480Profile(t)
	csv, err := os.ReadFile(p.ManualCSV)
	if err != nil {
		t.Fatalf("reading %s: %v", p.ManualCSV, err)
	}
	for _, tc := range []struct {
		name, from, to string
	}{
		{"non-zero p2", "000,00,0,", "000,07,0,"},
		{"non-zero p3", "000,00,0,", "000,00,7,"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			mutated := bytes.Replace(csv, []byte(tc.from), []byte(tc.to), 1)
			if bytes.Equal(mutated, csv) {
				t.Fatalf("the fixture did not change anything: %q not found in %s", tc.from, p.ManualCSV)
			}
			if _, err := extable.ParseCSV(p, mutated); err == nil {
				t.Fatal("ParseCSV accepted the row; an address component no EX frame can carry would have been dropped into the inventory as a 0")
			}
		})
	}
}

// TestParseCSV_RefusesATextRow pins TextRowsAbsent from the refusing side.
// This chart prints no free-text field — the nearest candidates, the five
// PF-key rows 048-052, carry a numeric "00 ~ 99 (2-digit)" legend — so the
// profile declares TextRowsAbsent with TextWidth 0, and a row flagged text is
// a transcription error rather than a row with an unstated width.
//
// The mutation flags menu 000 as text at ITS OWN width, so what is refused is
// the FLAG and not a width mismatch: under TextRowsAbsent there is no width
// that would make the row legal.
func TestParseCSV_RefusesATextRow(t *testing.T) {
	p := ts480Profile(t)
	if p.TextRowPolicy != extable.TextRowsAbsent || p.TextWidth != 0 {
		t.Fatalf("profile declares TextRowPolicy %v / TextWidth %d, want TextRowsAbsent / 0", p.TextRowPolicy, p.TextWidth)
	}
	csv, err := os.ReadFile(p.ManualCSV)
	if err != nil {
		t.Fatalf("reading %s: %v", p.ManualCSV, err)
	}
	mutated := bytes.Replace(csv, []byte(",1,false,427"), []byte(",1,true,427"), 1)
	if bytes.Equal(mutated, csv) {
		t.Fatalf("the fixture did not change anything: menu 000's row was not found in %s in the expected shape", p.ManualCSV)
	}
	if _, err := extable.ParseCSV(p, mutated); err == nil {
		t.Error("ParseCSV accepted a text row under TextRowsAbsent; a chart with no free-text field would have published one")
	}
}

// dropLastDataRow returns csv with its final data line removed. It works on
// the LAST line rather than a named address so that it cannot silently become
// a no-op if a row is renumbered.
func dropLastDataRow(t *testing.T, csv []byte) []byte {
	t.Helper()
	lines := strings.Split(strings.TrimRight(string(csv), "\n"), "\n")
	if len(lines) == 0 {
		t.Fatal("the CSV is empty")
	}
	last := lines[len(lines)-1]
	if strings.HasPrefix(last, "#") {
		t.Fatalf("the CSV's last line is a comment, not a data row: %q", last)
	}
	return []byte(strings.Join(lines[:len(lines)-1], "\n") + "\n")
}

// names renders a profile set for a failure message.
func names(ps []extable.NamedProfile) []string {
	out := make([]string, 0, len(ps))
	for _, p := range ps {
		out = append(out, fmt.Sprintf("%s (%s.%s)", p.Name, p.Profile.Package, p.Profile.VarName))
	}
	return out
}
