// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by internal/fakets590/gen from transcription-b-590sg.csv. DO NOT EDIT.

package fakets590

// exWidths590SG is this row's EX (MENU) inventory in compact form: ONE WIDTH
// TOKEN PER MENU NUMBER, and THE STRING'S INDEX IS THE MENU NUMBER — this
// chart runs from 000 with no gaps (590:543-544). A token is '1'..'8', a
// field of that many raw ASCII bytes of P5. There is no text token:
// transcription B's text column is validated and deliberately not projected
// (gen/main.go's widthToken says why, and what that does and does not
// claim). ex.go expands this into the address -> default raw P5 map the
// fake answers from.
//
// THE ADDRESS IS A SINGLE COMPONENT: the chart's three-digit Menu number is
// the whole of it, and the frame's P2, P3 and P4 are printed constants
// (590:546-553) rather than address parts.
//
// It is a PROJECTION OF TRANSCRIPTION B — this package's own copy,
// transcription-b-590sg.csv — derived from that artefact's digits
// column alone. The codec's inventory for this row
// (core/kw/ts590) is generated from transcription A by different code, and
// core/transport's cross-check proves the two agree — so a defect in either
// transcription or either generator shows up there.
//
// 100 menus, 000 to 099. Regenerate with `go generate ./internal/fakets590`;
// gen/main_test.go refuses a file that has drifted from the CSV.
var exWidths590SG = "" +
	"4811122221" + // menus 000-009 — transcription-b-590sg.csv lines 2-11
	"1111111122" + // menus 010-019 — transcription-b-590sg.csv lines 12-21
	"1111111111" + // menus 020-029 — transcription-b-590sg.csv lines 22-31
	"1111111111" + // menus 030-039 — transcription-b-590sg.csv lines 32-41
	"2121111111" + // menus 040-049 — transcription-b-590sg.csv lines 42-51
	"1111111111" + // menus 050-059 — transcription-b-590sg.csv lines 52-61
	"1112111111" + // menus 060-069 — transcription-b-590sg.csv lines 62-71
	"1111111211" + // menus 070-079 — transcription-b-590sg.csv lines 72-81
	"1111111333" + // menus 080-089 — transcription-b-590sg.csv lines 82-91
	"3333333333" // menus 090-099 — transcription-b-590sg.csv lines 92-101
