// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by internal/fakedx101/gen from transcription-b.csv. DO NOT EDIT.

package fakedx101

// exGroups is this fake's EX (MENU) inventory in compact form: one entry per
// (P1,P2) subgroup, in the chart's own order, with one width token per P3 item
// in P3 order starting at 01. A token is '1'..'4' — a numeric field of that many
// raw ASCII bytes — or 'T', the 12-byte text field. ex.go expands it into the
// address -> default raw P4 map the fake answers from, and states what the
// table does and does not claim.
//
// ONE TABLE SERVES BOTH MODELS. The manual prints Table 2 once for the
// FTDX101D and the FTDX101MP, so a NewD radio and a NewMP one answer EX reads
// identically; the two differ on this wire in the ID answer and nowhere else.
//
// It is a PROJECTION OF TRANSCRIPTION B (transcription-b.csv), derived from that
// artefact's digits column and its own text flag, and from nothing else. The
// dialect's inventory (core/cat/ftdx101/exinventory_gen.go) is generated from
// transcription A by different code, and core/transport's cross-check proves the
// two agree — so a defect in either transcription or either generator shows up
// there.
//
// 18 subgroups, 193 items. Regenerate with `go generate ./internal/fakedx101`;
// gen/main_test.go refuses a file that has drifted from the CSV.
var exGroups = []struct{ p1, p2, widths string }{
	{"01", "01", "44421211311131"},          // 14 items — RADIO SETTING / MODE SSB, transcription-b.csv lines 44-57
	{"01", "02", "444212113114131"},         // 15 items — RADIO SETTING / MODE AM, transcription-b.csv lines 58-72
	{"01", "03", "4442121131413144"},        // 16 items — RADIO SETTING / MODE FM, transcription-b.csv lines 73-88
	{"01", "04", "4441421211311131"},        // 16 items — RADIO SETTING / MODE PSK/DATA, transcription-b.csv lines 89-104
	{"01", "05", "44411212113111"},          // 14 items — RADIO SETTING / MODE RTTY, transcription-b.csv lines 105-118
	{"01", "06", "11113"},                   // 5 items — RADIO SETTING / ENC/DEC PSK, transcription-b.csv lines 119-123
	{"01", "07", "111111"},                  // 6 items — RADIO SETTING / ENC/DEC RTTY, transcription-b.csv lines 124-129
	{"02", "01", "44421211311211111"},       // 17 items — CW SETTING / MODE CW, transcription-b.csv lines 130-146
	{"02", "02", "1111214111112"},           // 13 items — CW SETTING / KEYER, transcription-b.csv lines 147-159
	{"02", "03", "1"},                       // 1 item — CW SETTING / DECODE CW, transcription-b.csv line 160
	{"03", "01", "11111311111111113211322"}, // 23 items — OPERATION SETTING / GENERAL, transcription-b.csv lines 161-183
	{"03", "02", "13221"},                   // 5 items — OPERATION SETTING / RX-DSP, transcription-b.csv lines 184-188
	{"03", "03", "11232232232232232232"},    // 20 items — OPERATION SETTING / TX AUDIO, transcription-b.csv lines 189-208
	{"03", "04", "3333131"},                 // 7 items — OPERATION SETTING / TX GNRL, transcription-b.csv lines 209-215
	{"03", "05", "1111111"},                 // 7 items — OPERATION SETTING / TUNING, transcription-b.csv lines 216-222
	{"04", "01", "T1122221"},                // 8 items — DISPLAY SETTING / DISPLAY, transcription-b.csv lines 223-230
	{"04", "02", "1111"},                    // 4 items — DISPLAY SETTING / SCOPE, transcription-b.csv lines 231-234
	{"04", "03", "11"},                      // 2 items — DISPLAY SETTING / EXT-MONITOR, transcription-b.csv lines 235-236
}
