// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by internal/fakeft991a/gen from transcription-b.csv. DO NOT EDIT.

package fakeft991a

// exItems is this fake's EX (MENU) inventory: one entry per menu address, in
// the chart's own order, with the raw P4 reply WIDTH that address answers as a
// token '1'..'8' — a numeric field of that many raw ASCII bytes. There is NO
// text token: this chart's transcription carries no column from which a text
// item could be identified, so every row is projected as numeric
// (gen/main.go's widthToken says what that does and does not claim).
// ex.go expands this into the address -> default raw P4 map the fake answers
// from, and states what the table does and does not claim.
//
// THE ADDRESS IS A SINGLE COMPONENT: the chart's three-digit MENU Number is the
// whole address, with P2 and P3 zero (core/cat's EXAddressSingle), which is why
// this radio's EX read frame is six bytes — the narrowest in the family. There
// are no groups, so this is a flat list rather than the FT-891's widths
// strings.
//
// It is a PROJECTION OF TRANSCRIPTION B (transcription-b.csv), derived from that
// artefact's digits column alone. The dialect's inventory
// (core/cat/ft991a/exinventory_gen.go) is generated from transcription A by
// different code, and core/transport's cross-check proves the two agree — so a
// defect in either transcription or either generator shows up there.
//
// EVERY ENTRY'S SOURCE LINE IS ITS ADDRESS PLUS ONE, and no line number is
// repeated below because of it: the chart's menu numbers are one consecutive
// run from 001, which gen/main.go's checkRun enforces rather than assumes.
//
// The exItem type is declared in ex.go, not here: this file is DATA, and a
// type declared in it would be a second thing a hand-edit could reach.
//
// EXCLUDED, and counted in that run: 087 (transcription-b.csv line 88),
// whose digits cell is this transcription's no-parameter token. The chart
// prints that row with no parameter at all, so it names no field an EX frame
// could read or write (gen/main.go's parameterlessToken, and plan decision
// P18 on why the two transcriptions spell one printed hyphen differently).
//
// 152 items of a 153-row chart. Regenerate with `go generate ./internal/fakeft991a`;
// gen/main_test.go refuses a file that has drifted from the CSV.
var exItems = []exItem{
	{"001", '4'},
	{"002", '4'},
	{"003", '4'},
	{"004", '1'},
	{"005", '1'},
	{"006", '1'},
	{"007", '1'},
	{"008", '2'},
	{"009", '1'},
	{"010", '3'},
	{"011", '3'},
	{"012", '1'},
	{"013", '1'},
	{"014", '2'},
	{"015", '3'},
	{"016", '1'},
	{"017", '4'},
	{"018", '1'},
	{"019", '1'},
	{"020", '1'},
	{"021", '1'},
	{"022", '1'},
	{"023", '1'},
	{"024", '1'},
	{"025", '2'},
	{"026", '3'},
	{"027", '5'},
	{"028", '1'},
	{"029", '1'},
	{"030", '1'},
	{"031", '1'},
	{"032", '1'},
	{"033", '1'},
	{"034", '1'},
	{"035", '3'},
	{"036", '2'},
	{"037", '1'},
	{"038", '1'},
	{"039", '3'},
	{"040", '1'},
	{"041", '2'},
	{"042", '1'},
	{"043", '2'},
	{"044", '1'},
	{"045", '1'},
	{"046", '3'},
	{"047", '1'},
	{"048", '1'},
	{"049", '3'},
	{"050", '2'},
	{"051", '1'},
	{"052", '2'},
	{"053", '1'},
	{"054", '3'},
	{"055", '1'},
	{"056", '1'},
	{"057", '4'},
	{"058", '1'},
	{"059", '1'},
	{"060", '1'},
	{"061", '1'},
	{"062", '1'},
	{"063", '1'},
	{"064", '5'},
	{"065", '5'},
	{"066", '2'},
	{"067", '1'},
	{"068", '1'},
	{"069", '2'},
	{"070", '1'},
	{"071", '1'},
	{"072", '1'},
	{"073", '3'},
	{"074", '1'},
	{"075", '3'},
	{"076", '1'},
	{"077", '1'},
	{"078", '3'},
	{"079", '1'},
	{"080", '4'},
	{"081", '4'},
	{"082", '4'},
	{"083", '5'},
	{"084", '1'},
	{"085", '1'},
	{"086", '1'},
	{"088", '1'},
	{"089", '1'},
	{"090", '1'},
	{"091", '1'},
	{"092", '2'},
	{"093", '1'},
	{"094", '2'},
	{"095", '1'},
	{"096", '1'},
	{"097", '1'},
	{"098", '1'},
	{"099", '3'},
	{"100", '1'},
	{"101", '1'},
	{"102", '2'},
	{"103", '1'},
	{"104", '2'},
	{"105", '1'},
	{"106", '1'},
	{"107", '3'},
	{"108", '1'},
	{"109", '1'},
	{"110", '1'},
	{"111", '1'},
	{"112", '3'},
	{"113", '2'},
	{"114", '1'},
	{"115", '1'},
	{"116", '2'},
	{"117", '1'},
	{"118", '1'},
	{"119", '2'},
	{"120", '3'},
	{"121", '2'},
	{"122", '2'},
	{"123", '3'},
	{"124", '2'},
	{"125", '2'},
	{"126", '3'},
	{"127", '2'},
	{"128", '2'},
	{"129", '3'},
	{"130", '2'},
	{"131", '2'},
	{"132", '3'},
	{"133", '2'},
	{"134", '2'},
	{"135", '3'},
	{"136", '2'},
	{"137", '3'},
	{"138", '3'},
	{"139", '3'},
	{"140", '3'},
	{"141", '1'},
	{"142", '1'},
	{"143", '3'},
	{"144", '4'},
	{"145", '3'},
	{"146", '3'},
	{"147", '4'},
	{"148", '3'},
	{"149", '1'},
	{"150", '1'},
	{"151", '8'},
	{"152", '1'},
	{"153", '2'},
}
