// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {codeplug} from '../models';

export function CancelTransfer():Promise<void>;

export function ConfirmSend(arg1:string,arg2:string):Promise<void>;

export function Connect(arg1:string,arg2:string):Promise<main.ConnectionInfo>;

export function ConnectDemo(arg1:string):Promise<main.ConnectionInfo>;

export function DiffAgainstRadio():Promise<main.DiffView>;

export function Disconnect():Promise<void>;

export function ExportCSV():Promise<string>;

export function GetAppVersion():Promise<main.VersionView>;

export function GetCodeplug():Promise<main.CodeplugView>;

export function GetSettings():Promise<main.SettingsView>;

export function GetSettingsSpec():Promise<main.SettingsSpecView>;

export function GetSupportedModels():Promise<Array<string>>;

export function GetUISpec():Promise<main.UISpecView>;

export function GetUnverifiedWriteConsent(arg1:string):Promise<main.UnverifiedWriteConsentView>;

export function ImportCHIRP():Promise<main.ImportResultView>;

export function ImportCSV():Promise<main.ImportResultView>;

export function IsDirty():Promise<boolean>;

export function ListPorts():Promise<Array<main.PortEntry>>;

export function ListUnverifiedWriteConsents():Promise<Array<main.UnverifiedWriteConsentView>>;

export function LoadFile():Promise<main.CodeplugView>;

export function PrepareSend():Promise<main.SendPlanView>;

export function ReadRadio():Promise<main.CodeplugView>;

export function ReadSettingsRadio():Promise<main.SettingsView>;

export function SaveFile(arg1:string):Promise<void>;

export function SaveFileAs():Promise<string>;

export function SetUnverifiedWriteConsent(arg1:string,arg2:boolean):Promise<void>;

export function UpdateChannel(arg1:codeplug.Channel):Promise<main.EditResult>;

export function UpdateChannels(arg1:Array<codeplug.Channel>):Promise<main.EditResult>;

export function Validate():Promise<main.ValidationView>;
