// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTransfer() {
  return window['go']['main']['App']['CancelTransfer']();
}

export function ConfirmSend(arg1, arg2) {
  return window['go']['main']['App']['ConfirmSend'](arg1, arg2);
}

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function ConnectDemo(arg1) {
  return window['go']['main']['App']['ConnectDemo'](arg1);
}

export function DiffAgainstRadio() {
  return window['go']['main']['App']['DiffAgainstRadio']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function ExportCSV() {
  return window['go']['main']['App']['ExportCSV']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetCodeplug() {
  return window['go']['main']['App']['GetCodeplug']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSettingsSpec() {
  return window['go']['main']['App']['GetSettingsSpec']();
}

export function GetSupportedModels() {
  return window['go']['main']['App']['GetSupportedModels']();
}

export function GetUISpec() {
  return window['go']['main']['App']['GetUISpec']();
}

export function ImportCHIRP() {
  return window['go']['main']['App']['ImportCHIRP']();
}

export function ImportCSV() {
  return window['go']['main']['App']['ImportCSV']();
}

export function IsDirty() {
  return window['go']['main']['App']['IsDirty']();
}

export function ListPorts() {
  return window['go']['main']['App']['ListPorts']();
}

export function LoadFile() {
  return window['go']['main']['App']['LoadFile']();
}

export function PrepareSend() {
  return window['go']['main']['App']['PrepareSend']();
}

export function ReadRadio() {
  return window['go']['main']['App']['ReadRadio']();
}

export function ReadSettingsRadio() {
  return window['go']['main']['App']['ReadSettingsRadio']();
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function SaveFileAs() {
  return window['go']['main']['App']['SaveFileAs']();
}

export function UpdateChannel(arg1) {
  return window['go']['main']['App']['UpdateChannel'](arg1);
}

export function UpdateChannels(arg1) {
  return window['go']['main']['App']['UpdateChannels'](arg1);
}

export function Validate() {
  return window['go']['main']['App']['Validate']();
}
