// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by internal/fakeft891/gen from transcription-b.csv. DO NOT EDIT.

package fakeft891

// exGroups is this fake's EX (MENU) inventory in compact form: one entry per
// P1 group, in the chart's own order, with one width token per P2 item in P2
// order starting at 01. A token is '1'..'5' — a numeric field of that many raw
// ASCII bytes. There is NO text token: this chart's transcription carries no
// column from which a text item could be identified, so every row is projected
// as numeric (gen/main.go's widthToken says what that does and does not claim).
// ex.go expands this into the address -> default raw P4 map the fake answers
// from, and states what the table does and does not claim.
//
// THE ADDRESS IS A PAIR: the chart's four-digit MENU Number is P1 then P2, and
// every item's P3 is zero (core/cat's EXAddressPair), which is why this radio's
// EX read frame is seven bytes where every registered sibling's is nine.
//
// It is a PROJECTION OF TRANSCRIPTION B (transcription-b.csv), derived from that
// artefact's digits column alone. The dialect's inventory
// (core/cat/ft891/exinventory_gen.go) is generated from transcription A by
// different code, and core/transport's cross-check proves the two agree — so a
// defect in either transcription or either generator shows up there.
//
// 18 groups, 159 items. Regenerate with `go generate ./internal/fakeft891`;
// gen/main_test.go refuses a file that has drifted from the CSV.
var exGroups = []struct{ p1, widths string }{
	{"01", "444"},                     // 3 items — transcription-b.csv lines 2-4
	{"02", "2222111"},                 // 7 items — transcription-b.csv lines 5-11
	{"03", "33"},                      // 2 items — transcription-b.csv lines 12-13
	{"04", "11231411111"},             // 11 items — transcription-b.csv lines 14-24
	{"05", "11231111111132113111"},    // 20 items — transcription-b.csv lines 25-44
	{"06", "2121131"},                 // 7 items — transcription-b.csv lines 45-51
	{"07", "2121311141111"},           // 13 items — transcription-b.csv lines 52-64
	{"08", "115521211131"},            // 12 items — transcription-b.csv lines 65-76
	{"09", "131411"},                  // 6 items — transcription-b.csv lines 77-82
	{"10", "21211113111"},             // 11 items — transcription-b.csv lines 83-93
	{"11", "212113111"},               // 9 items — transcription-b.csv lines 94-102
	{"12", "1321"},                    // 4 items — transcription-b.csv lines 103-106
	{"13", "11"},                      // 2 items — transcription-b.csv lines 107-108
	{"14", "1111111"},                 // 7 items — transcription-b.csv lines 109-115
	{"15", "232232232232232232"},      // 18 items — transcription-b.csv lines 116-133
	{"16", "33333333333333113433431"}, // 23 items — transcription-b.csv lines 134-156
	{"17", "1"},                       // 1 item — transcription-b.csv line 157
	{"18", "444"},                     // 3 items — transcription-b.csv lines 158-160
}
