// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by internal/fakedx10/gen from transcription-b.csv. DO NOT EDIT.

package fakedx10

// exGroups is this fake's EX (MENU) inventory in compact form: one entry per
// (P1,P2) subgroup, in the chart's own order, with one width token per P3 item
// in P3 order starting at 01. A token is '1'..'4' — a numeric field of that many
// raw ASCII bytes — or 'T', the 12-byte text field. ex.go expands it into the
// address -> default raw P4 map the fake answers from, and states what the
// table does and does not claim.
//
// It is a PROJECTION OF TRANSCRIPTION B (transcription-b.csv), derived from that
// artefact's Digits column alone, with its P4 column consulted only to tell a
// text item from a numeric one. The dialect's inventory
// (core/cat/ftdx10/exinventory_gen.go) is generated from transcription A by
// different code, and core/transport's cross-check proves the two agree — so a
// defect in either transcription or either generator shows up there.
//
// 18 subgroups, 197 items. Regenerate with `go generate ./internal/fakedx10`;
// gen/main_test.go refuses a file that has drifted from the CSV.
var exGroups = []struct{ p1, p2, widths string }{
	{"01", "01", "3334442121311131"},      // 16 items — RADIO SETTING / MODE SSB, transcription-b.csv lines 2-17
	{"01", "02", "33344421213114131"},     // 17 items — RADIO SETTING / MODE AM, transcription-b.csv lines 18-34
	{"01", "03", "333444212131413144121"}, // 21 items — RADIO SETTING / MODE FM, transcription-b.csv lines 35-55
	{"01", "04", "333444142121311131"},    // 18 items — RADIO SETTING / MODE PSK/DATA, transcription-b.csv lines 56-73
	{"01", "05", "3334441121213111"},      // 16 items — RADIO SETTING / MODE RTTY, transcription-b.csv lines 74-89
	{"01", "06", "11113"},                 // 5 items — RADIO SETTING / ENC/DEC PSK, transcription-b.csv lines 90-94
	{"01", "07", "111111"},                // 6 items — RADIO SETTING / ENC/DEC RTTY, transcription-b.csv lines 95-100
	{"02", "01", "333444212131111111"},    // 18 items — CW SETTING / MODE CW, transcription-b.csv lines 101-118
	{"02", "02", "11214111112"},           // 11 items — CW SETTING / KEYER, transcription-b.csv lines 119-129
	{"02", "03", "1"},                     // 1 item — CW SETTING / DECODE CW, transcription-b.csv line 130
	{"03", "01", "11311111111113121132"},  // 20 items — OPERATION SETTING / GENERAL, transcription-b.csv lines 131-150
	{"03", "02", "1321"},                  // 4 items — OPERATION SETTING / RX-DSP, transcription-b.csv lines 151-154
	{"03", "03", "1232232232232232232"},   // 19 items — OPERATION SETTING / TX AUDIO, transcription-b.csv lines 155-173
	{"03", "04", "3333131"},               // 7 items — OPERATION SETTING / TX GENERAL, transcription-b.csv lines 174-180
	{"03", "05", "1111111"},               // 7 items — OPERATION SETTING / TUNING, transcription-b.csv lines 181-187
	{"04", "01", "T1122"},                 // 5 items — DISPLAY SETTING / DISPLAY, transcription-b.csv lines 188-192
	{"04", "02", "1111"},                  // 4 items — DISPLAY SETTING / SCOPE, transcription-b.csv lines 193-196
	{"04", "03", "11"},                    // 2 items — DISPLAY SETTING / EXT-MONITOR, transcription-b.csv lines 197-198
}
