// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by internal/extable/gen from table2.csv. DO NOT EDIT.

package ftdx101

import cat "github.com/gm5dna/open-rig-programmer/core/cat"

// exItems is the FTdx101D/MP's EX address inventory, sorted by (P1,P2,P3),
// built from ONE source: the manual transcription in table2.csv (the
// FTDX101MP/FTDX101D CAT manual rev 2308-L's Table 2 "MENU Chart"). It
// serves BOTH models: the ledger's applicability attestation records that
// no stored property is model-conditional. There are no hardware READ
// observations to join — no FTdx101 has ever been asked anything — so
// every item carries the absence sentinels ObservedReadWidth 0 and
// ObservedReadShape "". Regenerate with `go generate ./core/cat/ftdx101`;
// do not edit by hand.
var exItems = []cat.EXItem{
	{Addr: cat.EXAddress{P1: 1, P2: 1, P3: 1}, P1Label: "RADIO SETTING", P2Label: "MODE SSB", Name: "AGC FAST DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},          // manual line 717
	{Addr: cat.EXAddress{P1: 1, P2: 1, P3: 2}, P1Label: "RADIO SETTING", P2Label: "MODE SSB", Name: "AGC MID DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 718
	{Addr: cat.EXAddress{P1: 1, P2: 1, P3: 3}, P1Label: "RADIO SETTING", P2Label: "MODE SSB", Name: "AGC SLOW DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},          // manual line 719
	{Addr: cat.EXAddress{P1: 1, P2: 1, P3: 4}, P1Label: "RADIO SETTING", P2Label: "MODE SSB", Name: "LCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},               // manual line 720
	{Addr: cat.EXAddress{P1: 1, P2: 1, P3: 5}, P1Label: "RADIO SETTING", P2Label: "MODE SSB", Name: "LCUT SLOP", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},               // manual line 721
	{Addr: cat.EXAddress{P1: 1, P2: 1, P3: 6}, P1Label: "RADIO SETTING", P2Label: "MODE SSB", Name: "HCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},               // manual line 722
	{Addr: cat.EXAddress{P1: 1, P2: 1, P3: 7}, P1Label: "RADIO SETTING", P2Label: "MODE SSB", Name: "HCUT SLOPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},              // manual line 723
	{Addr: cat.EXAddress{P1: 1, P2: 1, P3: 8}, P1Label: "RADIO SETTING", P2Label: "MODE SSB", Name: "SSB OUT SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},          // manual line 724
	{Addr: cat.EXAddress{P1: 1, P2: 1, P3: 9}, P1Label: "RADIO SETTING", P2Label: "MODE SSB", Name: "SSB OUT LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 725
	{Addr: cat.EXAddress{P1: 1, P2: 1, P3: 10}, P1Label: "RADIO SETTING", P2Label: "MODE SSB", Name: "TX BPF SEL", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},             // manual line 726
	{Addr: cat.EXAddress{P1: 1, P2: 1, P3: 11}, P1Label: "RADIO SETTING", P2Label: "MODE SSB", Name: "SSB MOD SOURCE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},         // manual line 727
	{Addr: cat.EXAddress{P1: 1, P2: 1, P3: 12}, P1Label: "RADIO SETTING", P2Label: "MODE SSB", Name: "REAR SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},            // manual line 728
	{Addr: cat.EXAddress{P1: 1, P2: 1, P3: 13}, P1Label: "RADIO SETTING", P2Label: "MODE SSB", Name: "RPORT GAIN", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},             // manual line 729
	{Addr: cat.EXAddress{P1: 1, P2: 1, P3: 14}, P1Label: "RADIO SETTING", P2Label: "MODE SSB", Name: "RPTT SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},            // manual line 730
	{Addr: cat.EXAddress{P1: 1, P2: 2, P3: 1}, P1Label: "RADIO SETTING", P2Label: "MODE AM", Name: "AGC FAST DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 731
	{Addr: cat.EXAddress{P1: 1, P2: 2, P3: 2}, P1Label: "RADIO SETTING", P2Label: "MODE AM", Name: "AGC MID DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},            // manual line 732
	{Addr: cat.EXAddress{P1: 1, P2: 2, P3: 3}, P1Label: "RADIO SETTING", P2Label: "MODE AM", Name: "AGC SLOW DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 733
	{Addr: cat.EXAddress{P1: 1, P2: 2, P3: 4}, P1Label: "RADIO SETTING", P2Label: "MODE AM", Name: "LCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                // manual line 734
	{Addr: cat.EXAddress{P1: 1, P2: 2, P3: 5}, P1Label: "RADIO SETTING", P2Label: "MODE AM", Name: "LCUT SLOP", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                // manual line 735
	{Addr: cat.EXAddress{P1: 1, P2: 2, P3: 6}, P1Label: "RADIO SETTING", P2Label: "MODE AM", Name: "HCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                // manual line 736
	{Addr: cat.EXAddress{P1: 1, P2: 2, P3: 7}, P1Label: "RADIO SETTING", P2Label: "MODE AM", Name: "HCUT SLOPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},               // manual line 737
	{Addr: cat.EXAddress{P1: 1, P2: 2, P3: 8}, P1Label: "RADIO SETTING", P2Label: "MODE AM", Name: "AM OUT SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},            // manual line 739
	{Addr: cat.EXAddress{P1: 1, P2: 2, P3: 9}, P1Label: "RADIO SETTING", P2Label: "MODE AM", Name: "AM OUT LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},             // manual line 741
	{Addr: cat.EXAddress{P1: 1, P2: 2, P3: 10}, P1Label: "RADIO SETTING", P2Label: "MODE AM", Name: "TX BPF SEL", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},              // manual line 742
	{Addr: cat.EXAddress{P1: 1, P2: 2, P3: 11}, P1Label: "RADIO SETTING", P2Label: "MODE AM", Name: "AM MOD SOURCE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 743
	{Addr: cat.EXAddress{P1: 1, P2: 2, P3: 12}, P1Label: "RADIO SETTING", P2Label: "MODE AM", Name: "MIC GAIN", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                // manual line 744
	{Addr: cat.EXAddress{P1: 1, P2: 2, P3: 13}, P1Label: "RADIO SETTING", P2Label: "MODE AM", Name: "REAR SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},             // manual line 745
	{Addr: cat.EXAddress{P1: 1, P2: 2, P3: 14}, P1Label: "RADIO SETTING", P2Label: "MODE AM", Name: "RPORT GAIN", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},              // manual line 746
	{Addr: cat.EXAddress{P1: 1, P2: 2, P3: 15}, P1Label: "RADIO SETTING", P2Label: "MODE AM", Name: "RPTT SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},             // manual line 747
	{Addr: cat.EXAddress{P1: 1, P2: 3, P3: 1}, P1Label: "RADIO SETTING", P2Label: "MODE FM", Name: "AGC FAST DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 748
	{Addr: cat.EXAddress{P1: 1, P2: 3, P3: 2}, P1Label: "RADIO SETTING", P2Label: "MODE FM", Name: "AGC MID DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},            // manual line 749
	{Addr: cat.EXAddress{P1: 1, P2: 3, P3: 3}, P1Label: "RADIO SETTING", P2Label: "MODE FM", Name: "AGC SLOW DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 750
	{Addr: cat.EXAddress{P1: 1, P2: 3, P3: 4}, P1Label: "RADIO SETTING", P2Label: "MODE FM", Name: "LCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                // manual line 751
	{Addr: cat.EXAddress{P1: 1, P2: 3, P3: 5}, P1Label: "RADIO SETTING", P2Label: "MODE FM", Name: "LCUT SLOP", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                // manual line 752
	{Addr: cat.EXAddress{P1: 1, P2: 3, P3: 6}, P1Label: "RADIO SETTING", P2Label: "MODE FM", Name: "HCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                // manual line 753
	{Addr: cat.EXAddress{P1: 1, P2: 3, P3: 7}, P1Label: "RADIO SETTING", P2Label: "MODE FM", Name: "HCUT SLOPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},               // manual line 754
	{Addr: cat.EXAddress{P1: 1, P2: 3, P3: 8}, P1Label: "RADIO SETTING", P2Label: "MODE FM", Name: "FM OUT SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},            // manual line 755
	{Addr: cat.EXAddress{P1: 1, P2: 3, P3: 9}, P1Label: "RADIO SETTING", P2Label: "MODE FM", Name: "FM OUT LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},             // manual line 756
	{Addr: cat.EXAddress{P1: 1, P2: 3, P3: 10}, P1Label: "RADIO SETTING", P2Label: "MODE FM", Name: "FM MOD SOURCE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 757
	{Addr: cat.EXAddress{P1: 1, P2: 3, P3: 11}, P1Label: "RADIO SETTING", P2Label: "MODE FM", Name: "MIC GAIN", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                // manual line 758
	{Addr: cat.EXAddress{P1: 1, P2: 3, P3: 12}, P1Label: "RADIO SETTING", P2Label: "MODE FM", Name: "REAR SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},             // manual line 759
	{Addr: cat.EXAddress{P1: 1, P2: 3, P3: 13}, P1Label: "RADIO SETTING", P2Label: "MODE FM", Name: "RPORT GAIN", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},              // manual line 760
	{Addr: cat.EXAddress{P1: 1, P2: 3, P3: 14}, P1Label: "RADIO SETTING", P2Label: "MODE FM", Name: "RPTT SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},             // manual line 761
	{Addr: cat.EXAddress{P1: 1, P2: 3, P3: 15}, P1Label: "RADIO SETTING", P2Label: "MODE FM", Name: "RPT SHIFT(28MHz)", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 762
	{Addr: cat.EXAddress{P1: 1, P2: 3, P3: 16}, P1Label: "RADIO SETTING", P2Label: "MODE FM", Name: "RPT SHIFT(50MHz)", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 763
	{Addr: cat.EXAddress{P1: 1, P2: 4, P3: 1}, P1Label: "RADIO SETTING", P2Label: "MODE PSK/DATA", Name: "AGC FAST DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 764
	{Addr: cat.EXAddress{P1: 1, P2: 4, P3: 2}, P1Label: "RADIO SETTING", P2Label: "MODE PSK/DATA", Name: "AGC MID DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 765
	{Addr: cat.EXAddress{P1: 1, P2: 4, P3: 3}, P1Label: "RADIO SETTING", P2Label: "MODE PSK/DATA", Name: "AGC SLOW DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 766
	{Addr: cat.EXAddress{P1: 1, P2: 4, P3: 4}, P1Label: "RADIO SETTING", P2Label: "MODE PSK/DATA", Name: "PSK TONE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 767
	{Addr: cat.EXAddress{P1: 1, P2: 4, P3: 5}, P1Label: "RADIO SETTING", P2Label: "MODE PSK/DATA", Name: "DATA SHIFT (SSB)", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 768
	{Addr: cat.EXAddress{P1: 1, P2: 4, P3: 6}, P1Label: "RADIO SETTING", P2Label: "MODE PSK/DATA", Name: "LCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},          // manual line 769
	{Addr: cat.EXAddress{P1: 1, P2: 4, P3: 7}, P1Label: "RADIO SETTING", P2Label: "MODE PSK/DATA", Name: "LCUT SLOP", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},          // manual line 770
	{Addr: cat.EXAddress{P1: 1, P2: 4, P3: 8}, P1Label: "RADIO SETTING", P2Label: "MODE PSK/DATA", Name: "HCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},          // manual line 771
	{Addr: cat.EXAddress{P1: 1, P2: 4, P3: 9}, P1Label: "RADIO SETTING", P2Label: "MODE PSK/DATA", Name: "HCUT SLOPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},         // manual line 772
	{Addr: cat.EXAddress{P1: 1, P2: 4, P3: 10}, P1Label: "RADIO SETTING", P2Label: "MODE PSK/DATA", Name: "DATA OUT SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 773
	{Addr: cat.EXAddress{P1: 1, P2: 4, P3: 11}, P1Label: "RADIO SETTING", P2Label: "MODE PSK/DATA", Name: "DATA OUT LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 774
	{Addr: cat.EXAddress{P1: 1, P2: 4, P3: 12}, P1Label: "RADIO SETTING", P2Label: "MODE PSK/DATA", Name: "TX BPF SEL", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 775
	{Addr: cat.EXAddress{P1: 1, P2: 4, P3: 13}, P1Label: "RADIO SETTING", P2Label: "MODE PSK/DATA", Name: "DATA MOD SOURCE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 776
	{Addr: cat.EXAddress{P1: 1, P2: 4, P3: 14}, P1Label: "RADIO SETTING", P2Label: "MODE PSK/DATA", Name: "REAR SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 777
	{Addr: cat.EXAddress{P1: 1, P2: 4, P3: 15}, P1Label: "RADIO SETTING", P2Label: "MODE PSK/DATA", Name: "RPORT GAIN", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 778
	{Addr: cat.EXAddress{P1: 1, P2: 4, P3: 16}, P1Label: "RADIO SETTING", P2Label: "MODE PSK/DATA", Name: "RPTT SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 779
	{Addr: cat.EXAddress{P1: 1, P2: 5, P3: 1}, P1Label: "RADIO SETTING", P2Label: "MODE RTTY", Name: "AGC FAST DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},         // manual line 780
	{Addr: cat.EXAddress{P1: 1, P2: 5, P3: 2}, P1Label: "RADIO SETTING", P2Label: "MODE RTTY", Name: "AGC MID DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},          // manual line 781
	{Addr: cat.EXAddress{P1: 1, P2: 5, P3: 3}, P1Label: "RADIO SETTING", P2Label: "MODE RTTY", Name: "AGC SLOW DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},         // manual line 782
	{Addr: cat.EXAddress{P1: 1, P2: 5, P3: 4}, P1Label: "RADIO SETTING", P2Label: "MODE RTTY", Name: "POLARITY-RX", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},            // manual line 783
	{Addr: cat.EXAddress{P1: 1, P2: 5, P3: 5}, P1Label: "RADIO SETTING", P2Label: "MODE RTTY", Name: "POLARITY-TX", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},            // manual line 784
	{Addr: cat.EXAddress{P1: 1, P2: 5, P3: 6}, P1Label: "RADIO SETTING", P2Label: "MODE RTTY", Name: "LCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},              // manual line 785
	{Addr: cat.EXAddress{P1: 1, P2: 5, P3: 7}, P1Label: "RADIO SETTING", P2Label: "MODE RTTY", Name: "LCUT SLOP", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},              // manual line 786
	{Addr: cat.EXAddress{P1: 1, P2: 5, P3: 8}, P1Label: "RADIO SETTING", P2Label: "MODE RTTY", Name: "HCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},              // manual line 787
	{Addr: cat.EXAddress{P1: 1, P2: 5, P3: 9}, P1Label: "RADIO SETTING", P2Label: "MODE RTTY", Name: "HCUT SLOPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},             // manual line 788
	{Addr: cat.EXAddress{P1: 1, P2: 5, P3: 10}, P1Label: "RADIO SETTING", P2Label: "MODE RTTY", Name: "DATA OUT SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 789
	{Addr: cat.EXAddress{P1: 1, P2: 5, P3: 11}, P1Label: "RADIO SETTING", P2Label: "MODE RTTY", Name: "RTTY OUT LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 790
	{Addr: cat.EXAddress{P1: 1, P2: 5, P3: 12}, P1Label: "RADIO SETTING", P2Label: "MODE RTTY", Name: "SHIFT PORT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},            // manual line 791
	{Addr: cat.EXAddress{P1: 1, P2: 5, P3: 13}, P1Label: "RADIO SETTING", P2Label: "MODE RTTY", Name: "MARK FREQUENCY", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 792
	{Addr: cat.EXAddress{P1: 1, P2: 5, P3: 14}, P1Label: "RADIO SETTING", P2Label: "MODE RTTY", Name: "SHIFT FREQUENCY", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 793
	{Addr: cat.EXAddress{P1: 1, P2: 6, P3: 1}, P1Label: "RADIO SETTING", P2Label: "ENC/DEC PSK", Name: "PSK MODE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},             // manual line 794
	{Addr: cat.EXAddress{P1: 1, P2: 6, P3: 2}, P1Label: "RADIO SETTING", P2Label: "ENC/DEC PSK", Name: "DECODE AFC RANGE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 795
	{Addr: cat.EXAddress{P1: 1, P2: 6, P3: 3}, P1Label: "RADIO SETTING", P2Label: "ENC/DEC PSK", Name: "QPSK POLARITY RX", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 797
	{Addr: cat.EXAddress{P1: 1, P2: 6, P3: 4}, P1Label: "RADIO SETTING", P2Label: "ENC/DEC PSK", Name: "QPSK POLARITY TX", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 799
	{Addr: cat.EXAddress{P1: 1, P2: 6, P3: 5}, P1Label: "RADIO SETTING", P2Label: "ENC/DEC PSK", Name: "PSK TX LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},         // manual line 800
	{Addr: cat.EXAddress{P1: 1, P2: 7, P3: 1}, P1Label: "RADIO SETTING", P2Label: "ENC/DEC RTTY", Name: "RX USOS", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},             // manual line 808
	{Addr: cat.EXAddress{P1: 1, P2: 7, P3: 2}, P1Label: "RADIO SETTING", P2Label: "ENC/DEC RTTY", Name: "TX USOS", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},             // manual line 809
	{Addr: cat.EXAddress{P1: 1, P2: 7, P3: 3}, P1Label: "RADIO SETTING", P2Label: "ENC/DEC RTTY", Name: "RX NEW LINE CODE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 810
	{Addr: cat.EXAddress{P1: 1, P2: 7, P3: 4}, P1Label: "RADIO SETTING", P2Label: "ENC/DEC RTTY", Name: "TX AUTO CR+LF", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},       // manual line 811
	{Addr: cat.EXAddress{P1: 1, P2: 7, P3: 5}, P1Label: "RADIO SETTING", P2Label: "ENC/DEC RTTY", Name: "TX DIDDLE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 812
	{Addr: cat.EXAddress{P1: 1, P2: 7, P3: 6}, P1Label: "RADIO SETTING", P2Label: "ENC/DEC RTTY", Name: "BAUDOT CODE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},         // manual line 813
	{Addr: cat.EXAddress{P1: 2, P2: 1, P3: 1}, P1Label: "CW SETTING", P2Label: "MODE CW", Name: "AGC FAST DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},              // manual line 814
	{Addr: cat.EXAddress{P1: 2, P2: 1, P3: 2}, P1Label: "CW SETTING", P2Label: "MODE CW", Name: "AGC MID DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},               // manual line 815
	{Addr: cat.EXAddress{P1: 2, P2: 1, P3: 3}, P1Label: "CW SETTING", P2Label: "MODE CW", Name: "AGC SLOW DELAY", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},              // manual line 816
	{Addr: cat.EXAddress{P1: 2, P2: 1, P3: 4}, P1Label: "CW SETTING", P2Label: "MODE CW", Name: "LCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                   // manual line 817
	{Addr: cat.EXAddress{P1: 2, P2: 1, P3: 5}, P1Label: "CW SETTING", P2Label: "MODE CW", Name: "LCUT SLOP", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                   // manual line 818
	{Addr: cat.EXAddress{P1: 2, P2: 1, P3: 6}, P1Label: "CW SETTING", P2Label: "MODE CW", Name: "HCUT FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                   // manual line 819
	{Addr: cat.EXAddress{P1: 2, P2: 1, P3: 7}, P1Label: "CW SETTING", P2Label: "MODE CW", Name: "HCUT SLOPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                  // manual line 820
	{Addr: cat.EXAddress{P1: 2, P2: 1, P3: 8}, P1Label: "CW SETTING", P2Label: "MODE CW", Name: "CW OUT SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},               // manual line 821
	{Addr: cat.EXAddress{P1: 2, P2: 1, P3: 9}, P1Label: "CW SETTING", P2Label: "MODE CW", Name: "CW OUT LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                // manual line 822
	{Addr: cat.EXAddress{P1: 2, P2: 1, P3: 10}, P1Label: "CW SETTING", P2Label: "MODE CW", Name: "CW AUTO MODE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},               // manual line 823
	{Addr: cat.EXAddress{P1: 2, P2: 1, P3: 11}, P1Label: "CW SETTING", P2Label: "MODE CW", Name: "CW BK-IN TYPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},              // manual line 824
	{Addr: cat.EXAddress{P1: 2, P2: 1, P3: 12}, P1Label: "CW SETTING", P2Label: "MODE CW", Name: "CW BK-IN DELAY", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},             // manual line 826
	{Addr: cat.EXAddress{P1: 2, P2: 1, P3: 13}, P1Label: "CW SETTING", P2Label: "MODE CW", Name: "CW WAVE SHAPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},              // manual line 828
	{Addr: cat.EXAddress{P1: 2, P2: 1, P3: 14}, P1Label: "CW SETTING", P2Label: "MODE CW", Name: "CW FREQ DISPLAY", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},            // manual line 829
	{Addr: cat.EXAddress{P1: 2, P2: 1, P3: 15}, P1Label: "CW SETTING", P2Label: "MODE CW", Name: "PC KEYING", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                  // manual line 830
	{Addr: cat.EXAddress{P1: 2, P2: 1, P3: 16}, P1Label: "CW SETTING", P2Label: "MODE CW", Name: "QSK DELAY TIME", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},             // manual line 832
	{Addr: cat.EXAddress{P1: 2, P2: 1, P3: 17}, P1Label: "CW SETTING", P2Label: "MODE CW", Name: "CW INDICATOR", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},               // manual line 834
	{Addr: cat.EXAddress{P1: 2, P2: 2, P3: 1}, P1Label: "CW SETTING", P2Label: "KEYER", Name: "F KEYER TYPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                  // manual line 835
	{Addr: cat.EXAddress{P1: 2, P2: 2, P3: 2}, P1Label: "CW SETTING", P2Label: "KEYER", Name: "F KEYER DOT/DASH", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},              // manual line 836
	{Addr: cat.EXAddress{P1: 2, P2: 2, P3: 3}, P1Label: "CW SETTING", P2Label: "KEYER", Name: "R KEYER TYPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                  // manual line 837
	{Addr: cat.EXAddress{P1: 2, P2: 2, P3: 4}, P1Label: "CW SETTING", P2Label: "KEYER", Name: "R KEYER DOT/DASH", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},              // manual line 838
	{Addr: cat.EXAddress{P1: 2, P2: 2, P3: 5}, P1Label: "CW SETTING", P2Label: "KEYER", Name: "CW WEIGHT", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                     // manual line 839
	{Addr: cat.EXAddress{P1: 2, P2: 2, P3: 6}, P1Label: "CW SETTING", P2Label: "KEYER", Name: "NUMBER STYLE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                  // manual line 840
	{Addr: cat.EXAddress{P1: 2, P2: 2, P3: 7}, P1Label: "CW SETTING", P2Label: "KEYER", Name: "CONTEST NUMBER", Digits: 4, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                // manual line 842
	{Addr: cat.EXAddress{P1: 2, P2: 2, P3: 8}, P1Label: "CW SETTING", P2Label: "KEYER", Name: "CW MEMORY 1", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                   // manual line 844
	{Addr: cat.EXAddress{P1: 2, P2: 2, P3: 9}, P1Label: "CW SETTING", P2Label: "KEYER", Name: "CW MEMORY 2", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                   // manual line 845
	{Addr: cat.EXAddress{P1: 2, P2: 2, P3: 10}, P1Label: "CW SETTING", P2Label: "KEYER", Name: "CW MEMORY 3", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                  // manual line 846
	{Addr: cat.EXAddress{P1: 2, P2: 2, P3: 11}, P1Label: "CW SETTING", P2Label: "KEYER", Name: "CW MEMORY 4", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                  // manual line 847
	{Addr: cat.EXAddress{P1: 2, P2: 2, P3: 12}, P1Label: "CW SETTING", P2Label: "KEYER", Name: "CW MEMORY 5", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                  // manual line 848
	{Addr: cat.EXAddress{P1: 2, P2: 2, P3: 13}, P1Label: "CW SETTING", P2Label: "KEYER", Name: "REPEAT INTERVAL", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},              // manual line 849
	{Addr: cat.EXAddress{P1: 2, P2: 3, P3: 1}, P1Label: "CW SETTING", P2Label: "DECODE CW", Name: "CW DECODE BW", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},              // manual line 851
	{Addr: cat.EXAddress{P1: 3, P2: 1, P3: 1}, P1Label: "OPERATION SETTING", P2Label: "GENERAL", Name: "DECODE RX SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 853
	{Addr: cat.EXAddress{P1: 3, P2: 1, P3: 2}, P1Label: "OPERATION SETTING", P2Label: "GENERAL", Name: "HEADPHONE MIX", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 854
	{Addr: cat.EXAddress{P1: 3, P2: 1, P3: 3}, P1Label: "OPERATION SETTING", P2Label: "GENERAL", Name: "ANT3 SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},          // manual line 855
	{Addr: cat.EXAddress{P1: 3, P2: 1, P3: 4}, P1Label: "OPERATION SETTING", P2Label: "GENERAL", Name: "NB WIDTH", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},             // manual line 856
	{Addr: cat.EXAddress{P1: 3, P2: 1, P3: 5}, P1Label: "OPERATION SETTING", P2Label: "GENERAL", Name: "NB REJECTION", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},         // manual line 857
	{Addr: cat.EXAddress{P1: 3, P2: 1, P3: 6}, P1Label: "OPERATION SETTING", P2Label: "GENERAL", Name: "BEEP LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 858
	{Addr: cat.EXAddress{P1: 3, P2: 1, P3: 7}, P1Label: "OPERATION SETTING", P2Label: "GENERAL", Name: "RF/SQL VR", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},            // manual line 859
	{Addr: cat.EXAddress{P1: 3, P2: 1, P3: 8}, P1Label: "OPERATION SETTING", P2Label: "GENERAL", Name: "TUNER SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},         // manual line 860
	{Addr: cat.EXAddress{P1: 3, P2: 1, P3: 9}, P1Label: "OPERATION SETTING", P2Label: "GENERAL", Name: "232C RATE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},            // manual line 861
	{Addr: cat.EXAddress{P1: 3, P2: 1, P3: 10}, P1Label: "OPERATION SETTING", P2Label: "GENERAL", Name: "232C TIME OUT TIMER", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""}, // manual line 862
	{Addr: cat.EXAddress{P1: 3, P2: 1, P3: 11}, P1Label: "OPERATION SETTING", P2Label: "GENERAL", Name: "CAT RATE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},            // manual line 863
	{Addr: cat.EXAddress{P1: 3, P2: 1, P3: 12}, P1Label: "OPERATION SETTING", P2Label: "GENERAL", Name: "CAT TIME OUT TIMER", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 864
	{Addr: cat.EXAddress{P1: 3, P2: 1, P3: 13}, P1Label: "OPERATION SETTING", P2Label: "GENERAL", Name: "CAT RTS", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},             // manual line 865
	{Addr: cat.EXAddress{P1: 3, P2: 1, P3: 14}, P1Label: "OPERATION SETTING", P2Label: "GENERAL", Name: "QMB CH", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},              // manual line 867
	{Addr: cat.EXAddress{P1: 3, P2: 1, P3: 15}, P1Label: "OPERATION SETTING", P2Label: "GENERAL", Name: "MEM GROUP", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 869
	{Addr: cat.EXAddress{P1: 3, P2: 1, P3: 16}, P1Label: "OPERATION SETTING", P2Label: "GENERAL", Name: "QUICK SPLIT INPUT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 870
	{Addr: cat.EXAddress{P1: 3, P2: 1, P3: 17}, P1Label: "OPERATION SETTING", P2Label: "GENERAL", Name: "QUICK SPLIT FREQ", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 871
	{Addr: cat.EXAddress{P1: 3, P2: 1, P3: 18}, P1Label: "OPERATION SETTING", P2Label: "GENERAL", Name: "TX TIME OUT TIMER", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 872
	{Addr: cat.EXAddress{P1: 3, P2: 1, P3: 19}, P1Label: "OPERATION SETTING", P2Label: "GENERAL", Name: "MIC SCAN", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},            // manual line 873
	{Addr: cat.EXAddress{P1: 3, P2: 1, P3: 20}, P1Label: "OPERATION SETTING", P2Label: "GENERAL", Name: "MIC SCAN RESUME", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 874
	{Addr: cat.EXAddress{P1: 3, P2: 1, P3: 21}, P1Label: "OPERATION SETTING", P2Label: "GENERAL", Name: "REF FREQ ADJ", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 875
	{Addr: cat.EXAddress{P1: 3, P2: 1, P3: 22}, P1Label: "OPERATION SETTING", P2Label: "GENERAL", Name: "CS DIAL", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},             // manual line 877
	{Addr: cat.EXAddress{P1: 3, P2: 1, P3: 23}, P1Label: "OPERATION SETTING", P2Label: "GENERAL", Name: "KEYBOARD LANGUAGE", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 881
	{Addr: cat.EXAddress{P1: 3, P2: 2, P3: 1}, P1Label: "OPERATION SETTING", P2Label: "RX-DSP", Name: "APF WIDTH", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},             // manual line 884
	{Addr: cat.EXAddress{P1: 3, P2: 2, P3: 2}, P1Label: "OPERATION SETTING", P2Label: "RX-DSP", Name: "CONTOUR LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},         // manual line 885
	{Addr: cat.EXAddress{P1: 3, P2: 2, P3: 3}, P1Label: "OPERATION SETTING", P2Label: "RX-DSP", Name: "CONTOUR WIDTH", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},         // manual line 887
	{Addr: cat.EXAddress{P1: 3, P2: 2, P3: 4}, P1Label: "OPERATION SETTING", P2Label: "RX-DSP", Name: "DNR LEVEL", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},             // manual line 889
	{Addr: cat.EXAddress{P1: 3, P2: 2, P3: 5}, P1Label: "OPERATION SETTING", P2Label: "RX-DSP", Name: "IF NOTCH WIDTH", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 890
	{Addr: cat.EXAddress{P1: 3, P2: 3, P3: 1}, P1Label: "OPERATION SETTING", P2Label: "TX AUDIO", Name: "PROC TYPE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 899
	{Addr: cat.EXAddress{P1: 3, P2: 3, P3: 2}, P1Label: "OPERATION SETTING", P2Label: "TX AUDIO", Name: "AMC RELEASE TIME", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 900
	{Addr: cat.EXAddress{P1: 3, P2: 3, P3: 3}, P1Label: "OPERATION SETTING", P2Label: "TX AUDIO", Name: "PRMTRC EQ1 FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 901
	{Addr: cat.EXAddress{P1: 3, P2: 3, P3: 4}, P1Label: "OPERATION SETTING", P2Label: "TX AUDIO", Name: "PRMTRC EQ1 LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 902
	{Addr: cat.EXAddress{P1: 3, P2: 3, P3: 5}, P1Label: "OPERATION SETTING", P2Label: "TX AUDIO", Name: "PRMTRC EQ1 BWTH", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 903
	{Addr: cat.EXAddress{P1: 3, P2: 3, P3: 6}, P1Label: "OPERATION SETTING", P2Label: "TX AUDIO", Name: "PRMTRC EQ2 FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 905
	{Addr: cat.EXAddress{P1: 3, P2: 3, P3: 7}, P1Label: "OPERATION SETTING", P2Label: "TX AUDIO", Name: "PRMTRC EQ2 LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 907
	{Addr: cat.EXAddress{P1: 3, P2: 3, P3: 8}, P1Label: "OPERATION SETTING", P2Label: "TX AUDIO", Name: "PRMTRC EQ2 BWTH", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 908
	{Addr: cat.EXAddress{P1: 3, P2: 3, P3: 9}, P1Label: "OPERATION SETTING", P2Label: "TX AUDIO", Name: "PRMTRC EQ3 FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},     // manual line 910
	{Addr: cat.EXAddress{P1: 3, P2: 3, P3: 10}, P1Label: "OPERATION SETTING", P2Label: "TX AUDIO", Name: "PRMTRC EQ3 LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 912
	{Addr: cat.EXAddress{P1: 3, P2: 3, P3: 11}, P1Label: "OPERATION SETTING", P2Label: "TX AUDIO", Name: "PRMTRC EQ3 BWTH", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 913
	{Addr: cat.EXAddress{P1: 3, P2: 3, P3: 12}, P1Label: "OPERATION SETTING", P2Label: "TX AUDIO", Name: "P PRMTRC EQ1 FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 914
	{Addr: cat.EXAddress{P1: 3, P2: 3, P3: 13}, P1Label: "OPERATION SETTING", P2Label: "TX AUDIO", Name: "P PRMTRC EQ1 LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""}, // manual line 915
	{Addr: cat.EXAddress{P1: 3, P2: 3, P3: 14}, P1Label: "OPERATION SETTING", P2Label: "TX AUDIO", Name: "P PRMTRC EQ1 BWTH", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 916
	{Addr: cat.EXAddress{P1: 3, P2: 3, P3: 15}, P1Label: "OPERATION SETTING", P2Label: "TX AUDIO", Name: "P PRMTRC EQ2 FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 918
	{Addr: cat.EXAddress{P1: 3, P2: 3, P3: 16}, P1Label: "OPERATION SETTING", P2Label: "TX AUDIO", Name: "P PRMTRC EQ2 LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""}, // manual line 920
	{Addr: cat.EXAddress{P1: 3, P2: 3, P3: 17}, P1Label: "OPERATION SETTING", P2Label: "TX AUDIO", Name: "P PRMTRC EQ2 BWTH", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 921
	{Addr: cat.EXAddress{P1: 3, P2: 3, P3: 18}, P1Label: "OPERATION SETTING", P2Label: "TX AUDIO", Name: "P PRMTRC EQ3 FREQ", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 923
	{Addr: cat.EXAddress{P1: 3, P2: 3, P3: 19}, P1Label: "OPERATION SETTING", P2Label: "TX AUDIO", Name: "P PRMTRC EQ3 LEVEL", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""}, // manual line 925
	{Addr: cat.EXAddress{P1: 3, P2: 3, P3: 20}, P1Label: "OPERATION SETTING", P2Label: "TX AUDIO", Name: "P PRMTRC EQ3 BWTH", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},  // manual line 926
	{Addr: cat.EXAddress{P1: 3, P2: 4, P3: 1}, P1Label: "OPERATION SETTING", P2Label: "TX GNRL", Name: "HF MAX POWER", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},         // manual line 927
	{Addr: cat.EXAddress{P1: 3, P2: 4, P3: 2}, P1Label: "OPERATION SETTING", P2Label: "TX GNRL", Name: "50M MAX POWER", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 928
	{Addr: cat.EXAddress{P1: 3, P2: 4, P3: 3}, P1Label: "OPERATION SETTING", P2Label: "TX GNRL", Name: "70M MAX POWER", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 929
	{Addr: cat.EXAddress{P1: 3, P2: 4, P3: 4}, P1Label: "OPERATION SETTING", P2Label: "TX GNRL", Name: "AM MAX POWER", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},         // manual line 931
	{Addr: cat.EXAddress{P1: 3, P2: 4, P3: 5}, P1Label: "OPERATION SETTING", P2Label: "TX GNRL", Name: "VOX SELECT", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 933
	{Addr: cat.EXAddress{P1: 3, P2: 4, P3: 6}, P1Label: "OPERATION SETTING", P2Label: "TX GNRL", Name: "DATA VOX GAIN", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 934
	{Addr: cat.EXAddress{P1: 3, P2: 4, P3: 7}, P1Label: "OPERATION SETTING", P2Label: "TX GNRL", Name: "EMERGENCY FREQ TX", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 935
	{Addr: cat.EXAddress{P1: 3, P2: 5, P3: 1}, P1Label: "OPERATION SETTING", P2Label: "TUNING", Name: "SSB/CW DIAL STEP", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 936
	{Addr: cat.EXAddress{P1: 3, P2: 5, P3: 2}, P1Label: "OPERATION SETTING", P2Label: "TUNING", Name: "RTTY/PSK DIAL STEP", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 937
	{Addr: cat.EXAddress{P1: 3, P2: 5, P3: 3}, P1Label: "OPERATION SETTING", P2Label: "TUNING", Name: "CH STEP", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},               // manual line 938
	{Addr: cat.EXAddress{P1: 3, P2: 5, P3: 4}, P1Label: "OPERATION SETTING", P2Label: "TUNING", Name: "AM CH STEP", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},            // manual line 940
	{Addr: cat.EXAddress{P1: 3, P2: 5, P3: 5}, P1Label: "OPERATION SETTING", P2Label: "TUNING", Name: "FM CH STEP", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},            // manual line 942
	{Addr: cat.EXAddress{P1: 3, P2: 5, P3: 6}, P1Label: "OPERATION SETTING", P2Label: "TUNING", Name: "MAIN STEPS PER REV.", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 943
	{Addr: cat.EXAddress{P1: 3, P2: 5, P3: 7}, P1Label: "OPERATION SETTING", P2Label: "TUNING", Name: "MPVD STEPS PER REV.", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},   // manual line 944
	{Addr: cat.EXAddress{P1: 4, P2: 1, P3: 1}, P1Label: "DISPLAY SETTING", P2Label: "DISPLAY", Name: "MY CALL.", Digits: 12, Text: true, ObservedReadWidth: 0, ObservedReadShape: ""},               // manual line 945
	{Addr: cat.EXAddress{P1: 4, P2: 1, P3: 2}, P1Label: "DISPLAY SETTING", P2Label: "DISPLAY", Name: "MY CALL TIME", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 946
	{Addr: cat.EXAddress{P1: 4, P2: 1, P3: 3}, P1Label: "DISPLAY SETTING", P2Label: "DISPLAY", Name: "SCREEN SAVER", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 947
	{Addr: cat.EXAddress{P1: 4, P2: 1, P3: 4}, P1Label: "DISPLAY SETTING", P2Label: "DISPLAY", Name: "TFT CONTRAST", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},           // manual line 948
	{Addr: cat.EXAddress{P1: 4, P2: 1, P3: 5}, P1Label: "DISPLAY SETTING", P2Label: "DISPLAY", Name: "DIMMER TFT", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},             // manual line 950
	{Addr: cat.EXAddress{P1: 4, P2: 1, P3: 6}, P1Label: "DISPLAY SETTING", P2Label: "DISPLAY", Name: "DIMMER LED", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},             // manual line 951
	{Addr: cat.EXAddress{P1: 4, P2: 1, P3: 7}, P1Label: "DISPLAY SETTING", P2Label: "DISPLAY", Name: "MOUSE POINTER SPEED", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 953
	{Addr: cat.EXAddress{P1: 4, P2: 1, P3: 8}, P1Label: "DISPLAY SETTING", P2Label: "DISPLAY", Name: "FREQ STYLE", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},             // manual line 956
	{Addr: cat.EXAddress{P1: 4, P2: 2, P3: 1}, P1Label: "DISPLAY SETTING", P2Label: "SCOPE", Name: "RBW", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                      // manual line 957
	{Addr: cat.EXAddress{P1: 4, P2: 2, P3: 2}, P1Label: "DISPLAY SETTING", P2Label: "SCOPE", Name: "SCOPE CTR", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                // manual line 958
	{Addr: cat.EXAddress{P1: 4, P2: 2, P3: 3}, P1Label: "DISPLAY SETTING", P2Label: "SCOPE", Name: "2D DISP SENSITIVITY", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},      // manual line 959
	{Addr: cat.EXAddress{P1: 4, P2: 2, P3: 4}, P1Label: "DISPLAY SETTING", P2Label: "SCOPE", Name: "3DSS DISP SENSITIVITY", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},    // manual line 960
	{Addr: cat.EXAddress{P1: 4, P2: 3, P3: 1}, P1Label: "DISPLAY SETTING", P2Label: "EXT-MONITOR", Name: "EXT DISPLAY", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},        // manual line 961
	{Addr: cat.EXAddress{P1: 4, P2: 3, P3: 2}, P1Label: "DISPLAY SETTING", P2Label: "EXT-MONITOR", Name: "PIXEL", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},              // manual line 962
}
