// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by internal/extable/gen from menu590s.csv. DO NOT EDIT.

package ts590

import kw "github.com/gm5dna/open-rig-programmer/core/kw"

// exItems590S is the TS-590S's EX menu inventory, sorted by menu number,
// built from ONE source: the manual transcription in menu590s.csv (the
// TS-590S/TS-590SG PC Control Command Reference Guide's "EX Command
// Parameter List (for TS-590S)"). It is NOT the TS-590SG's table: the book
// prints two separate lists over colliding addresses with different
// meanings, and exItems590SG is the other one. The TS-590S's EX address is
// a SINGLE component: the chart's three-digit Menu number is P1, every
// item's P2 and P3 are 0, and the chart prints no group labels, so every
// P1Label and P2Label is "". There are no hardware READ observations to
// join — no TS-590S has ever been asked anything — so every item carries
// the absence sentinels ObservedReadWidth 0 and ObservedReadShape "".
// Regenerate with `go generate ./core/kw/ts590`; do not edit by hand.
var exItems590S = []kw.EXItem{
	{Addr: kw.EXAddress{P1: 0, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Display brightness", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                                 // manual line 569
	{Addr: kw.EXAddress{P1: 1, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Back light color", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                                   // manual line 570
	{Addr: kw.EXAddress{P1: 2, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Panel key response for double function", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                             // manual line 571
	{Addr: kw.EXAddress{P1: 3, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Beep volume", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                                        // manual line 573
	{Addr: kw.EXAddress{P1: 4, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Sidetone volume", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                                    // manual line 574
	{Addr: kw.EXAddress{P1: 5, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Message playback volume", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                            // manual line 575
	{Addr: kw.EXAddress{P1: 6, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Voice guide volume", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                                 // manual line 576
	{Addr: kw.EXAddress{P1: 7, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Voice guide speed", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                                  // manual line 577
	{Addr: kw.EXAddress{P1: 8, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Voice guide language", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                               // manual line 578
	{Addr: kw.EXAddress{P1: 9, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Auto announcement", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                                  // manual line 579
	{Addr: kw.EXAddress{P1: 10, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "MHz step (MHz)", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                                    // manual line 580
	{Addr: kw.EXAddress{P1: 11, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Tuning control adjustment rate (Hz)", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                               // manual line 589
	{Addr: kw.EXAddress{P1: 12, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "MULTI/CH control rounding off process", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                             // manual line 592
	{Addr: kw.EXAddress{P1: 13, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Dedicated step change inside the BC band (AM)", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                     // manual line 595
	{Addr: kw.EXAddress{P1: 14, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "MULTI/CH control step change for SSB/CW/FSK (kHz)", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                 // manual line 598
	{Addr: kw.EXAddress{P1: 15, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "MULTI/CH control step change for AM (kHz)", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                         // manual line 601
	{Addr: kw.EXAddress{P1: 16, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "MULTI/CH control step change for FM (kHz)", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                         // manual line 604
	{Addr: kw.EXAddress{P1: 17, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Maximum number of Quick Memory channels", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                           // manual line 607
	{Addr: kw.EXAddress{P1: 18, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Temporary variable of the standard memory frequency", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},               // manual line 610
	{Addr: kw.EXAddress{P1: 19, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Program Scan slow down function", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                   // manual line 613
	{Addr: kw.EXAddress{P1: 20, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Program Scan slow down frequency range (Hz)", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                       // manual line 616
	{Addr: kw.EXAddress{P1: 21, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Program Scan hold", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                                 // manual line 618
	{Addr: kw.EXAddress{P1: 22, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Scan Resume method", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                                // manual line 619
	{Addr: kw.EXAddress{P1: 23, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Auto mode change", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                                  // manual line 620
	{Addr: kw.EXAddress{P1: 24, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Following speed setting of AUTO NOTCH", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                             // manual line 622
	{Addr: kw.EXAddress{P1: 25, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "SSB/AM Low Cut transmit filter (Hz)", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                               // manual line 625
	{Addr: kw.EXAddress{P1: 26, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "SSB/AM High Cut transmit filter (Hz)", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                              // manual line 628
	{Addr: kw.EXAddress{P1: 27, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "SSB-DATA Low Cut transmit filter (Hz)", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                             // manual line 631
	{Addr: kw.EXAddress{P1: 28, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "SSB-DATA High Cut transmit filter (Hz)", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                            // manual line 634
	{Addr: kw.EXAddress{P1: 29, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Effective change of Speech Processor", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                              // manual line 637
	{Addr: kw.EXAddress{P1: 30, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Transmit equalizer", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                                // manual line 639
	{Addr: kw.EXAddress{P1: 31, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Receive equalizer", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                                 // manual line 640
	{Addr: kw.EXAddress{P1: 32, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Electronic keyer operation mode", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                   // manual line 642
	{Addr: kw.EXAddress{P1: 33, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Insert keying ON/OFF", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                              // manual line 644
	{Addr: kw.EXAddress{P1: 34, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Side tone/ pitch frequency setting (Hz)", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                           // manual line 646
	{Addr: kw.EXAddress{P1: 35, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "CW clipping (ms)", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                                  // manual line 648
	{Addr: kw.EXAddress{P1: 36, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Keying weight ratio", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                               // manual line 650
	{Addr: kw.EXAddress{P1: 37, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Reverse keying auto weight ratio", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                  // manual line 652
	{Addr: kw.EXAddress{P1: 38, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Bug key function", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                                  // manual line 654
	{Addr: kw.EXAddress{P1: 39, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Paddle dot/dash replacement setting", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                               // manual line 656
	{Addr: kw.EXAddress{P1: 40, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Mic paddle function", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                               // manual line 658
	{Addr: kw.EXAddress{P1: 41, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Auto CW TX in SSB mode", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                            // manual line 659
	{Addr: kw.EXAddress{P1: 42, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Frequency correction for changing SSB to CW mode", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                  // manual line 661
	{Addr: kw.EXAddress{P1: 43, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Break-in null configuration at time of keying speed configuration", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""}, // manual line 664
	{Addr: kw.EXAddress{P1: 44, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "FSK shift", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                                         // manual line 666
	{Addr: kw.EXAddress{P1: 45, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "FSK keying polarity", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                               // manual line 667
	{Addr: kw.EXAddress{P1: 46, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "FSK tone frequency (Hz)", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                           // manual line 668
	{Addr: kw.EXAddress{P1: 47, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Mic gain for FM", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                                   // manual line 669
	{Addr: kw.EXAddress{P1: 48, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Power fine", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                                        // manual line 670
	{Addr: kw.EXAddress{P1: 49, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Time-out Timer", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                                    // manual line 671
	{Addr: kw.EXAddress{P1: 50, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Configuring the Transverter function and power down", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},               // manual line 673
	{Addr: kw.EXAddress{P1: 51, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "TX hold when AT completes the tuning", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                              // manual line 676
	{Addr: kw.EXAddress{P1: 52, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "AT operation when receiving", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                       // manual line 678
	{Addr: kw.EXAddress{P1: 53, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "HF linear amplifier control", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                       // manual line 679
	{Addr: kw.EXAddress{P1: 54, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "50 MHz linear amplifier control", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                   // manual line 680
	{Addr: kw.EXAddress{P1: 55, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Constant recording", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                                // manual line 681
	{Addr: kw.EXAddress{P1: 56, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Voice/ message playback repeat", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                    // manual line 683
	{Addr: kw.EXAddress{P1: 57, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Voice/ message playback repeat duration (seconds)", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                 // manual line 686
	{Addr: kw.EXAddress{P1: 58, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Split transfer function", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                           // manual line 688
	{Addr: kw.EXAddress{P1: 59, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Write split transfer data to the VFO", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                              // manual line 690
	{Addr: kw.EXAddress{P1: 60, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Transmit inhibit", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                                  // manual line 700
	{Addr: kw.EXAddress{P1: 61, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "COM port communication speed", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                      // manual line 701
	{Addr: kw.EXAddress{P1: 62, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "USB port communication speed", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                      // manual line 703
	{Addr: kw.EXAddress{P1: 63, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "DATA modulation line", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                              // manual line 705
	{Addr: kw.EXAddress{P1: 64, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "USB audio input level", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                             // manual line 706
	{Addr: kw.EXAddress{P1: 65, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "USB audio output level", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                            // manual line 707
	{Addr: kw.EXAddress{P1: 66, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "ACC2 terminal AF input level", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                      // manual line 708
	{Addr: kw.EXAddress{P1: 67, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "ACC2 terminal AF output level", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                     // manual line 709
	{Addr: kw.EXAddress{P1: 68, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "External AF output beep mix", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                       // manual line 710
	{Addr: kw.EXAddress{P1: 69, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "DATA VOX", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                                          // manual line 711
	{Addr: kw.EXAddress{P1: 70, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "DATA VOX delay", Digits: 2, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                                    // manual line 713
	{Addr: kw.EXAddress{P1: 71, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "DATA VOX gain for USB audio input", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                 // manual line 715
	{Addr: kw.EXAddress{P1: 72, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "DATA VOX gain for ACC2 terminal input", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                             // manual line 718
	{Addr: kw.EXAddress{P1: 73, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "PKS polarity change", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                               // manual line 720
	{Addr: kw.EXAddress{P1: 74, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Busy transmit inhibit", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                             // manual line 721
	{Addr: kw.EXAddress{P1: 75, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "CTCSS mute operation change", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                       // manual line 723
	{Addr: kw.EXAddress{P1: 76, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "PSQ control signal logic selection", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                // manual line 726
	{Addr: kw.EXAddress{P1: 77, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "PSQ control signal output condition", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                               // manual line 729
	{Addr: kw.EXAddress{P1: 78, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "APO function (minutes)", Digits: 1, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                            // manual line 731
	{Addr: kw.EXAddress{P1: 79, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Panel PF A function", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                               // manual line 732
	{Addr: kw.EXAddress{P1: 80, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Panel PF B function", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                               // manual line 733
	{Addr: kw.EXAddress{P1: 81, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Mic PF 1 function", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                                 // manual line 734
	{Addr: kw.EXAddress{P1: 82, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Mic PF 2 function", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                                 // manual line 735
	{Addr: kw.EXAddress{P1: 83, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Mic PF 3 function", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                                 // manual line 737
	{Addr: kw.EXAddress{P1: 84, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Mic PF 4 function", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                                 // manual line 738
	{Addr: kw.EXAddress{P1: 85, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Mic PF (DWN) function", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                             // manual line 739
	{Addr: kw.EXAddress{P1: 86, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Mic PF (UP) function", Digits: 3, Text: false, ObservedReadWidth: 0, ObservedReadShape: ""},                                              // manual line 740
	{Addr: kw.EXAddress{P1: 87, P2: 0, P3: 0}, P1Label: "", P2Label: "", Name: "Power on message", Digits: 8, Text: true, ObservedReadWidth: 0, ObservedReadShape: ""},                                                   // manual line 741
}
